/* -----------------------------------------------------------------------------
  Filename:    CanSM_PBcfg.c
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: CanSM
               
               Configuration   : C:\Synergy\EA3\Working\Fiasa_326_327\Fiasa_326_327_03.01.00\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-10-28  14:31:37
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define CANSM_PBCFG_SOURCE
#include "CanSM_EcuM.h"
#define CANSM_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(CanSM_ConfigType, CANSM_PBCFG) CanSMConfiguration = 
{
  0x012200u, 
  CanSMBorTimeTxEnsured, 
  CanSMBorTimeL1, 
  CanSMBorTimeL2, 
  CanSMBorCounterL1ToL2
};

#define CANSM_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANSM_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeTxEnsured
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeTxEnsured[1] = 
{
  500u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeL1
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeL1[1] = 
{
  5u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeL2
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeL2[1] = 
{
  100u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorCounterL1ToL2
 ----------------------------------------------------------------------------- */

CONST(uint8, CANSM_PBCFG) CanSMBorCounterL1ToL2[1] = 
{
  20u
};



#define CANSM_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



