/* -----------------------------------------------------------------------------
  Filename:    Com_Cfg.c
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-06-09  13:23:34
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Misra / PClint justifications
 ----------------------------------------------------------------------------- */

/* PRQA S 0342 EOF */ /* MD_Com_0342 */
/* PRQA S 0850 EOF */ /* MD_MSR_19.8 */
/* PRQA S 0857 EOF */ /* MD_MSR_1.1 */
/* PRQA S 3453 EOF */ /* MD_MSR_19.7 */
/* PRQA S 3458 EOF */ /* MD_MSR_19.4 */


/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define V_IL_ASRCOM_CFG_SOURCE
#include "Com.h"
#if ((COM_RXINV == STD_ON) && (COM_SIGNAL_ACCESS_MACRO_API == STD_ON))
#include "Rte_Cbk.h"
#endif

/* -----------------------------------------------------------------------------
    &&&~ Rx Signal Invalidation Configuration Data
 ----------------------------------------------------------------------------- */

/* Rx signal invalidation is deactivated */


/* -----------------------------------------------------------------------------
    &&&~ Reception Filtering Configuration Data
 ----------------------------------------------------------------------------- */

/* Reception filtering is deactivated */


/* -----------------------------------------------------------------------------
    &&&~ Rx Deadline Monitoring Timeout Substitution Value
 ----------------------------------------------------------------------------- */

/* Feature is deactivated */


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */



