/* -----------------------------------------------------------------------------
  Filename:    Dcm_Lcfg.c
  Description: Generated tables of DCM.
               
               Manufacturer: Fiat
               Source file:  C:\Users\mzjphh\Desktop\Fiasa_326_327_05.01.00\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\System\Fiasa_326_327_F187_updated.cdd
               EcuDoc:       Nxtr_Electric_Power_Steering_P3272_P341_Next_Gen_A__FF_00_00_0002_00D2_P3272_P341_Next_Gen_A
               Variant:      _FF_00_00_0002_00D2_P3272_P341_Next_Gen_A

  Generated by GENy, 2017-03-06 18:15:28 -05:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2008-2017 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

#define DCM_LCFG_SOURCE
#include "Dcm.h"

/* RTE function prototypes */
#include "Rte_Dcm.h"
/* Vector Generated Information */
#include "v_par.h"


/* -----------------------------------------------------------------------------
    &&&~ Preprocessor constants (defines)
 ----------------------------------------------------------------------------- */

/* Check the compatibility of the generated files independent from the magic number check. */
#if !defined ( V_SUPPRESS_EXTENDED_VERSION_CHECK )
# if ( DIAG_ASRDCM_IMPLEMENTATION_MAJOR_VERSION != 0x04u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_MAJOR_VERSION with generated file!"
# endif
# if ( DIAG_ASRDCM_IMPLEMENTATION_MINOR_VERSION != 0x12u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_MINOR_VERSION with generated file!"
# endif
# if ( DIAG_ASRDCM_IMPLEMENTATION_PATCH_VERSION != 0x00u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_PATCH_VERSION with generated file!"
# endif
#endif



/* -----------------------------------------------------------------------------
    &&&~ Function prototypes
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

STATIC FUNC(void, DCM_CODE) DcmOnTimeoutDummyCallBack(Dcm_TimerIdType timerId);
STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyGetLength(Dcm_RteDataLenPtrType resDataLenPtr);
STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyCheckCondition(Dcm_NegativeResponseCodePtrType errorCodePtr);
STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_DspCall_DidServices_0xf1a2_ReadData(Dcm_RteDataPtrType resData); /* PRQA S 0779 */ /* AUTOSAR naming convention */
#define DCM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Uninitialized RAM 8Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_VAR_NOINIT_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

#if (DCM_DSL_PPRH_SUPPORT_ENABLED == STD_ON) || \
    (DCM_NUM_CONTEXTS > 1)
VAR(uint8, DCM_VAR_NOINIT) dcmPduTransportBuffer[DCM_DSL_CONCUR_BUFF_SIZE_CONST*DCM_DSL_NUM_TRANSP_OBJ_CONST];
#endif

STATIC VAR(uint8, DCM_VAR_NOINIT) dcmProtocolMainBuffer_0[4095];
#define DCM_STOP_SEC_VAR_NOINIT_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Uninitialized RAM unspecified definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

VAR(Dcm_TimerCounterType, DCM_VAR_NOINIT)  dcmTimerEngine[DCM_NUM_TIMERS_CONST];

VAR(Dcm_PduRxTransportInfoType, DCM_VAR_NOINIT) dcmPduRxTransportInfo[DCM_DSL_NUM_TRANSP_OBJ_CONST];
#if (DCM_DSL_SHARED_TX_CONN_ENABLED == STD_ON)
VAR(Dcm_PduTxTransportInfoType, DCM_VAR_NOINIT) dcmPduTxTransportInfo[DCM_DSL_NUM_TRANSP_OBJ_CONST];
#endif

/* Global variable of the current DCM state */
VAR(Dcm_StateIdType, DCM_VAR_NOINIT) dcmCurrentStateInfo[2];
VAR(Dcm_MemDidHandleType, DCM_VAR_NOINIT) dcm22_DidList[1][10];
VAR(Dcm_RteDataLenType, DCM_VAR_NOINIT) dcm22_DidResLen[1][10];
/* Global variable of the security access states */
VAR(Dcm_27_SecLevelStateMachineType, DCM_VAR_NOINIT) dcm27_SecLevelStateEngine[1];
#define DCM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 8Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* StateGroup Session descriptor table */
CONST(uint8, DCM_CONST) dcmStateValuesSession[5] = 
{
  0x01u, 
  0x02u, 
  0x03u, 
  0x7Eu, 
  0x40u
};
/* StateGroup SecurityAccess descriptor table */
CONST(uint8, DCM_CONST) dcmStateValuesSecurityAccess[2] = 
{
  0x00u, 
  0x01u
};
/* ServiceId look-up table. */
CONST(uint8, DCM_CONST) dcmDspServiceIdTypeList[13] = 
{
  12, 0x10u, 0xFFu, 0x14u, 0x19u, 0x22u, 0x27u, 0x28u, 0x2Eu, 0x2Fu, 0x31u, 0x3Eu, 0x85u		/* NXTR MANUAL EDIT */
};
/* Session sub-function id look up table */
CONST(uint8, DCM_CONST) dcm10_SubFuncLookUpTable[6] = 
{
  5, 
  0x01u, 
  0x02u, 
  0x03u, 
  0x7Eu, 
  0x40u
};
/* ResetType sub-function id look up table */
CONST(uint8, DCM_CONST) dcm11_SubFuncLookUpTable[3] = 
{
  0x00u	/* NXTR MANUAL EDIT */
};
/* Read DTC look-up table. */
CONST(uint8, DCM_CONST) dcm19_SubFuncLookUpTable[10] = 
{
  9, 0x01u, 0x02u, 0x04u, 0x06u, 0x07u, 0x08u, 0x09u, 
  0x0Cu, 0x0Eu
};
/* Supported SnapShotRecords by DEM */
CONST(uint8, DCM_CONST) dcm19_UsedSnpshtRecIds[2] = 
{
  0x01u, 0x00u
};
/* Supported ExtendedDataRecords by DEM */
CONST(uint8, DCM_CONST) dcm19_UsedExtDatRecIds[1] = 
{
  0x01u
};
/* Security access sub-function id look up table */
CONST(uint8, DCM_CONST) dcm27_SubFuncLookUpTable[2] = 
{
  1, 
  0x01u
};
/* Service 0x28  sub-function lookup table */
CONST(uint8, DCM_CONST) dcm28_SubFuncLookUpTable[3] = 
{
    2, 0x00u, 0x01u
};
/* Table of 0x2F DIDs' sub-function to control type mapping. */
CONST(uint8, DCM_CONST) dcm2F_SubFuncToCtrlTypeMap[4] = 
{
  0, 1, 3, 2
};
/* Table of 0x31 RIDs' sub-function to control type mapping. */
CONST(uint8, DCM_CONST) dcm31_SubFuncToCtrlTypeMap[4] = 
{
  4, 0, 1, 2
};
/* Control DTC Setting look-up table. */
CONST(uint8, DCM_CONST) dcm85_SubFuncLookUpTable[3] = 
{
  2, 0x01u, 0x02u
};
#define DCM_STOP_SEC_CONST_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 16Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_16BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* DID lookup table */
CONST(uint16, DCM_CONST) dcmDidLookUpTable[96] = 
{
  0x0100u, 0x0885u, 0x0AD9u, 0x0ADAu, 0x0ADBu, 0x0ADCu, 0x0ADEu, 0x1002u, 
  0x1004u, 0x1006u, 0x1008u, 0x1009u, 0x102Au, 0x191Du, 0x1921u, 0x2001u, 
  0x2002u, 0x2003u, 0x2008u, 0x200Au, 0x200Bu, 0x200Cu, 0x2010u, 0x2014u, 
  0x2023u, 0x2024u, 0x292Eu, 0x5051u, 0x5052u, 0x5AABu, 0xF100u, 0xF10Bu, 
  0xF10Du, 0xF154u, 0xF155u, 0xF158u, 0xF180u, 0xF181u, 0xF182u, 0xF183u, 
  0xF184u, 0xF185u, 0xF186u, 0xF187u, 0xF188u, 0xF18Cu, 0xF191u, 0xF192u, 
  0xF193u, 0xF194u, 0xF195u, 0xF1A0u, 0xF1A2u, 0xF1A3u, 0xF1A4u, 0xFD01u, 
  0xFD02u, 0xFD03u, 0xFD07u, 0xFD0Du, 0xFD0Eu, 0xFD10u, 0xFD11u, 0xFD12u, 
  0xFD13u, 0xFD14u, 0xFD17u, 0xFD19u, 0xFD1Au, 0xFD1Bu, 0xFD1Cu, 0xFD1Eu, 
  0xFD20u, 0xFD21u, 0xFD23u, 0xFD25u, 0xFD26u, 0xFD27u, 0xFD29u, 0xFD30u, 
  0xFD31u, 0xFDA1u, 0xFDA2u, 0xFDA3u, 0xFDACu, 0xFDADu, 0xFDAEu, 0xFDAFu, 
  0xFDB0u, 0xFDB1u, 0xFDB2u, 0xFDB3u, 0xFDB4u, 0xFDB5u, 0xFDB6u, 0xFDB7u
};
/* RID lookup table */
CONST(uint16, DCM_CONST) dcmRidLookUpTable[13] = 
{
   12, 0x0200u, 0xD001u, 0xD002u, 0xF000u, 0xF001u, 0xF003u, 0xF004u, 
  0xF005u, 0xF008u, 0xF009u, 0xF0FFu, 0xFEE0u
};
#define DCM_STOP_SEC_CONST_16BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 32Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_32BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

#if !defined ( V_SUPPRESS_EXTENDED_VERSION_CHECK )
  CONST(uint32, DCM_CONST) Dcm_GeneratorVersion = (uint32)0x041200;
#endif

#define DCM_STOP_SEC_CONST_32BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM unspecified definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* Context management */
#if (DCM_NUM_CONTEXTS > 1)
CONST(Dcm_MemTimerIdType, DCM_CONST) dcmTmrMgrContextP2TimerId[DCM_NUM_CONTEXTS] =
{
  DCM_TIMER_ID_P2_CONST,      /* UDS P2 Timer */
  DCM_TIMER_ID_OBD_P2_CONST   /* OBD P2 Timer */
};
#endif

/* Timer manager timeout notification callback table. */
CONST(Dcm_TimerTimeoutCallBackType, DCM_CONST) dcmTimerManagerInfo[4] = 
{
  DcmOnTimeoutSession, 
  DcmOnTimeoutResponsePending, 
  DcmOnTimeoutDummyCallBack, 
  DcmOnTimeoutDummyCallBack
};
/* RxPduIds property table. */
CONST(Dcm_RxPduInfoType, DCM_CONST) dcmDslRxPduInfoTable[2] = 
{
  { 0 }, 
  { 1 }
};
/* RxPduId mapping to connection */
CONST(Dcm_ConnectionRefType, DCM_CONST) dcmDslRxPdu2ConnMap[2][1] = 
{
  { 0 }, 
  { 0 }
};
/* TxPduIds connection reference table. */
CONST(Dcm_ConnectionRefType, DCM_CONST) dcmTxPduToConnTable[1] = 
{
  0
};
/* PDU connections property table. */
CONST(Dcm_PduConnectionType, DCM_CONST) dcmDslPduConnectionInfoTable[1] = 
{
  { 0, 0xF4u, 0, 0, 0, 0, 1, 4095, NULL_PTR }
};
/* PDU protocols property table. */
CONST(Dcm_PduProtocolType, DCM_CONST) dcmDslPduProtocolInfoTable[1] = 
{
  { { 0, 0 }, { 0, 0 }, 4095, dcmProtocolMainBuffer_0, NULL_PTR, NULL_PTR }
};
/* Service execution state-filter pool */
CONST(Dcm_StateMaskType, DCM_CONST) dcmServiceStateFilterPool[7][2] = 
{
  { 0x1Fu, 0x03u }, 
  { 0x1Du, 0x03u }, 
  { 0x1Au, 0x03u }, 
  { 0x1Cu, 0x03u }, 
  { 0x0Cu, 0x03u }, 
  { 0x08u, 0x03u }, 
  { 0x1Eu, 0x02u }
};
/* Service transition precondition state pool */
CONST(Dcm_StateMaskType, DCM_CONST) dcmStateTransPrecondInfo[7][2] = 
{
  { 0x1Fu, 0x02u }, 
  { 0x1Fu, 0x02u }, 
  { 0x1Du, 0x02u }, 
  { 0x1Fu, 0x02u }, 
  { 0x1Du, 0x02u }, 
  { 0x00u, 0x00u }, 
  { 0x00u, 0x01u }
};
/* Service transition target state index pool */
CONST(Dcm_StateIdType, DCM_CONST) dcmStateTransTargetInfo[7][2] = 
{
  {   0,   0 }, 
  {   1,   0 }, 
  {   2,   0 }, 
  {   3,   0 }, 
  {   4,   0 }, 
  {   0,   0 }, 
  {   0,   1 }
};
/* StateGroup descriptor table */
CONST(Dcm_StateGroupInfoType, DCM_CONST) dcmStateGroupInfo[2] = 
{
  { 5, 0x7Fu, dcmStateValuesSession, DcmOnChgStateSession }, 
  { 2, 0x33u, dcmStateValuesSecurityAccess, DcmOnChgStateSecurityAccess }
};
/* ServiceId property table. */
CONST(Dcm_ServiceTableType, DCM_CONST) dcmDspServiceInfoTable[13] = 
{
  { 0x1Fu, 2, 0, Dcm_DspDiagSessionControl, Dcm_DspInitDummyService, Dcm_DspPostDiagSessionControl } /* 0x10 */, 
  { 0x1Fu, 2, 0, Dcm_DspEcuReset, Dcm_DspInitDummyService, Dcm_DspPostEcuReset } /* 0x11 */, 
  { 0x0Fu, 4, 1, Dcm_DspClearDiagInfo, Dcm_DspInitDummyService, DiagSvc_DspPostClearDiagInfo } /* 0x14 */, 	/* NXTR MANUAL EDIT */
  { 0x1Fu, 2, 1, Dcm_DspReadDtcInfo, Dcm_DspInitDummyService, Dcm_DspPostReadDtcInfo } /* 0x19 */, 
  { 0x0Fu, 3, 0, Dcm_DspReadDataById, Dcm_DspInitReadDataById, Dcm_DspPostReadDataById } /* 0x22 */, 
  { 0x15u, 2, 2, Dcm_DspSecurityAccess, Dcm_DspInitSecurityAccess, Dcm_DspPostSecurityAccess } /* 0x27 */, 
  { 0x1Fu, 2, 3, Dcm_DspCommunicationControl, Dcm_DspInitDummyService, Dcm_DspPostCommunicationControl } /* 0x28 */, 
  { 0x0Fu, 4, 0, Dcm_DspWriteDataById, Dcm_DspInitWriteDataById, Dcm_DspPostWriteDataById } /* 0x2e */, 

  { 0x0Fu, 4, 0, Dcm_DspIoControlById, Dcm_DspInitDummyService, Dcm_DspPostDummyService } /* 0x2f */, 
  { 0x1Fu, 4, 0, Dcm_DspRoutineControl, Dcm_DspInitRoutineControl, Dcm_DspPostDummyService } /* 0x31 */, 
  { 0x1Fu, 2, 0, Dcm_DspTesterPresent, Dcm_DspInitDummyService, Dcm_DspPostDummyService } /* 0x3e */, 
  { 0x1Fu, 2, 4, Dcm_DspControlDtcSetting, Dcm_DspInitDummyService, Dcm_DspPostDummyService } /* 0x85 */, 
  { 0x0Fu, 1, 0, Dcm_DspUnknownService, Dcm_DspInitDummyService, Dcm_DspPostUnknownService } /* 0xff */
};
/* Session control information table. */
CONST(Dcm_SessionControlInfoType, DCM_CONST) dcm10_ServiceInfoTable[5] = 
{
  { { 50, 500 }, { 5, 500 }, 0, 0 } /* SubFuncId: 0x01 */, 
  { { 50, 500 }, { 5, 500 }, 0, 1 } /* SubFuncId: 0x02 */, 
  { { 50, 500 }, { 5, 500 }, 1, 2 } /* SubFuncId: 0x03 */, 
  { { 50, 500 }, { 5, 500 }, 0, 3 } /* SubFuncId: 0x7e */, 
  { { 50, 500 }, { 5, 500 }, 0, 4 } /* SubFuncId: 0x40 */
};
CONST(Dcm_10_RteChgPermCallBackType, DCM_CONST) dcm10_SesChgPermFunc = Rte_Call_SessionControl_GetSesChgPermission;
CONST(Dcm_10_RteChgIndCallBackType, DCM_CONST) dcm10_SesChgIndFunc = Rte_Call_SessionControl_ChangeIndication;
CONST(Dcm_10_RteRcrRpConfCallBackType, DCM_CONST) dcm10_RcrRpConfFunc = Rte_Call_SessionControl_ConfirmationRespPending;
CONST(Dcm_11_RtePermCallBackType, DCM_CONST) dcm11_EcuResetPermFunc = Rte_Call_ResetService_EcuReset;
/* EcuReset type specific execution states table. */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm11_ServiceInfoTable[2] = 
{
  0 /* SubFuncId: 0x01 */, 
  0 /* SubFuncId: 0x03 */
};
/* Read DTC property table. */
CONST(Dcm_19_SubFunctionInfoType, DCM_CONST) dcm19_ServiceInfoTable[9] = 
{
  { 0x02u, 1, 1, Dcm_DspReadDtcRNODTCBSM } /* SubFuncId: 0x01 */, 
  { 0x02u, 1, 1, Dcm_DspReadDtcRDTCBSM } /* SubFuncId: 0x02 */, 
  { 0x04u, 4, 1, Dcm_DspReadDtcRDTCSSBDTC } /* SubFuncId: 0x04 */, 
  { 0x10u, 4, 1, Dcm_DspReadDtcRDTCEDRBDN } /* SubFuncId: 0x06 */, 
  { 0x02u, 2, 1, Dcm_DspReadDtcRNODTCBSMR } /* SubFuncId: 0x07 */, 
  { 0x02u, 2, 1, Dcm_DspReadDtcRDTCBSMR } /* SubFuncId: 0x08 */, 
  { 0x80u, 3, 1, Dcm_DspReadDtcRSIODTC } /* SubFuncId: 0x09 */, 
  { 0x80u, 0, 1, Dcm_DspReadDtcRFCDTC } /* SubFuncId: 0x0c */, 
  { 0x80u, 0, 1, Dcm_DspReadDtcRMRCDTC } /* SubFuncId: 0x0e */
};
/* Service 0x22 DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm22_DidStateInfoTable[90] = 
{
   3 /* DID: 0x0100 */, 
   1 /* DID: 0x0885 */, 
   1 /* DID: 0x0ad9 */, 
   1 /* DID: 0x0ada */, 
   1 /* DID: 0x0adb */, 
   1 /* DID: 0x0adc */, 
   1 /* DID: 0x0ade */, 
   1 /* DID: 0x1002 */, 
   1 /* DID: 0x1004 */, 
   1 /* DID: 0x1006 */, 
   0 /* DID: 0x1008 */, 
   1 /* DID: 0x1009 */, 
   1 /* DID: 0x102a */, 
   1 /* DID: 0x191d */, 
   1 /* DID: 0x1921 */, 
   0 /* DID: 0x2001 */, 
   0 /* DID: 0x2002 */, 
   0 /* DID: 0x2003 */, 
   0 /* DID: 0x2008 */, 
   1 /* DID: 0x200a */, 
   1 /* DID: 0x200b */, 
   1 /* DID: 0x200c */, 
   0 /* DID: 0x2010 */, 
   0 /* DID: 0x2014 */, 
   1 /* DID: 0x2024 */, 
   1 /* DID: 0x292e */, 
   0 /* DID: 0xf100 */, 
   1 /* DID: 0xf10b */, 
   0 /* DID: 0xf10d */, 
   0 /* DID: 0xf154 */, 
   0 /* DID: 0xf155 */, 
   0 /* DID: 0xf158 */, 
   1 /* DID: 0xf180 */, 
   0 /* DID: 0xf181 */, 
   0 /* DID: 0xf182 */, 
   0 /* DID: 0xf183 */, 
   0 /* DID: 0xf184 */, 
   0 /* DID: 0xf185 */, 
   1 /* DID: 0xf186 */, 
   0 /* DID: 0xf187 */, 
   0 /* DID: 0xf188 */, 
   0 /* DID: 0xf18c */, 
   0 /* DID: 0xf191 */, 
   0 /* DID: 0xf192 */, 
   0 /* DID: 0xf193 */, 
   0 /* DID: 0xf194 */, 
   0 /* DID: 0xf195 */, 
   0 /* DID: 0xf1a0 */, 
   0 /* DID: 0xf1a2 */, 
   1 /* DID: 0xf1a3 */, 
   0 /* DID: 0xf1a4 */, 
   5 /* DID: 0xfd01 */, 
   5 /* DID: 0xfd02 */, 
   5 /* DID: 0xfd03 */, 
   5 /* DID: 0xfd07 */, 
   5 /* DID: 0xfd0e */, 
   5 /* DID: 0xfd10 */, 
   5 /* DID: 0xfd12 */, 
   5 /* DID: 0xfd13 */, 
   5 /* DID: 0xfd14 */, 
   5 /* DID: 0xfd17 */, 
   5 /* DID: 0xfd19 */, 
   5 /* DID: 0xfd1a */, 
   5 /* DID: 0xfd1b */, 
   5 /* DID: 0xfd1c */, 
   5 /* DID: 0xfd1e */, 
   5 /* DID: 0xfd20 */, 
   5 /* DID: 0xfd21 */, 
   5 /* DID: 0xfd23 */, 
   5 /* DID: 0xfd25 */, 
   5 /* DID: 0xfd26 */, 
   5 /* DID: 0xfd27 */, 
   5 /* DID: 0xfd29 */, 
   5 /* DID: 0xfd30 */, 
   5 /* DID: 0xfd31 */, 
   5 /* DID: 0xfda1 */, 
   5 /* DID: 0xfda2 */, 
   5 /* DID: 0xfda3 */, 
   5 /* DID: 0xfdac */, 
   5 /* DID: 0xfdad */, 
   5 /* DID: 0xfdae */, 
   5 /* DID: 0xfdaf */, 
   5 /* DID: 0xfdb0 */, 
   5 /* DID: 0xfdb1 */, 
   5 /* DID: 0xfdb2 */, 
   5 /* DID: 0xfdb3 */, 
   5 /* DID: 0xfdb4 */, 
   5 /* DID: 0xfdb5 */, 
   5 /* DID: 0xfdb6 */, 
   5 /* DID: 0xfdb7 */
};
/* Service 0x22 DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm22_DidHandleTable[91] = 
{
   90 /* Total size of the lookup table */, 
    0 /* DID: 0x0100 */, 
    1 /* DID: 0x0885 */, 
    2 /* DID: 0x0ad9 */, 
    3 /* DID: 0x0ada */, 
    4 /* DID: 0x0adb */, 
    5 /* DID: 0x0adc */, 
    6 /* DID: 0x0ade */, 
    7 /* DID: 0x1002 */, 
    8 /* DID: 0x1004 */, 
    9 /* DID: 0x1006 */, 
   10 /* DID: 0x1008 */, 
   11 /* DID: 0x1009 */, 
   12 /* DID: 0x102a */, 
   13 /* DID: 0x191d */, 
   14 /* DID: 0x1921 */, 
   15 /* DID: 0x2001 */, 
   16 /* DID: 0x2002 */, 
   17 /* DID: 0x2003 */, 
   18 /* DID: 0x2008 */, 
   19 /* DID: 0x200a */, 
   20 /* DID: 0x200b */, 
   21 /* DID: 0x200c */, 
   22 /* DID: 0x2010 */, 
   23 /* DID: 0x2014 */, 
   25 /* DID: 0x2024 */, 
   26 /* DID: 0x292e */, 
   30 /* DID: 0xf100 */, 
   31 /* DID: 0xf10b */, 
   32 /* DID: 0xf10d */, 
   33 /* DID: 0xf154 */, 
   34 /* DID: 0xf155 */, 
   35 /* DID: 0xf158 */, 
   36 /* DID: 0xf180 */, 
   37 /* DID: 0xf181 */, 
   38 /* DID: 0xf182 */, 
   39 /* DID: 0xf183 */, 
   40 /* DID: 0xf184 */, 
   41 /* DID: 0xf185 */, 
   42 /* DID: 0xf186 */, 
   43 /* DID: 0xf187 */, 
   44 /* DID: 0xf188 */, 
   45 /* DID: 0xf18c */, 
   46 /* DID: 0xf191 */, 
   47 /* DID: 0xf192 */, 
   48 /* DID: 0xf193 */, 
   49 /* DID: 0xf194 */, 
   50 /* DID: 0xf195 */, 
   51 /* DID: 0xf1a0 */, 
   52 /* DID: 0xf1a2 */, 
   53 /* DID: 0xf1a3 */, 
   54 /* DID: 0xf1a4 */, 
   55 /* DID: 0xfd01 */, 
   56 /* DID: 0xfd02 */, 
   57 /* DID: 0xfd03 */, 
   58 /* DID: 0xfd07 */, 
   60 /* DID: 0xfd0e */, 
   61 /* DID: 0xfd10 */, 
   63 /* DID: 0xfd12 */, 
   64 /* DID: 0xfd13 */, 
   65 /* DID: 0xfd14 */, 
   66 /* DID: 0xfd17 */, 
   67 /* DID: 0xfd19 */, 
   68 /* DID: 0xfd1a */, 
   69 /* DID: 0xfd1b */, 
   70 /* DID: 0xfd1c */, 
   71 /* DID: 0xfd1e */, 
   72 /* DID: 0xfd20 */, 
   73 /* DID: 0xfd21 */, 
   74 /* DID: 0xfd23 */, 
   75 /* DID: 0xfd25 */, 
   76 /* DID: 0xfd26 */, 
   77 /* DID: 0xfd27 */, 
   78 /* DID: 0xfd29 */, 
   79 /* DID: 0xfd30 */, 
   80 /* DID: 0xfd31 */, 
   81 /* DID: 0xfda1 */, 
   82 /* DID: 0xfda2 */, 
   83 /* DID: 0xfda3 */, 
   84 /* DID: 0xfdac */, 
   85 /* DID: 0xfdad */, 
   86 /* DID: 0xfdae */, 
   87 /* DID: 0xfdaf */, 
   88 /* DID: 0xfdb0 */, 
   89 /* DID: 0xfdb1 */, 
   90 /* DID: 0xfdb2 */, 
   91 /* DID: 0xfdb3 */, 
   92 /* DID: 0xfdb4 */, 
   93 /* DID: 0xfdb5 */, 
   94 /* DID: 0xfdb6 */, 
   95 /* DID: 0xfdb7 */
};
/* Service 0x22 DID property table */
CONST(Dcm_22_ServiceInfoType, DCM_CONST) dcm22_ServiceInfoTable[90] = 
{
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0100_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0100_ReadData } /* 0x0100 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0885_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0885_ReadData } /* 0x0885 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0ad9_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0ad9_ReadData } /* 0x0ad9 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0ada_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0ada_ReadData } /* 0x0ada */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0adb_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0adb_ReadData } /* 0x0adb */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0adc_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0adc_ReadData } /* 0x0adc */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0ade_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0ade_ReadData } /* 0x0ade */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1002_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1002_ReadData } /* 0x1002 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1004_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1004_ReadData } /* 0x1004 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1006_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1006_ReadData } /* 0x1006 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1008_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1008_ReadData } /* 0x1008 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1009_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1009_ReadData } /* 0x1009 */, 
  {  9, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x102a_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x102a_ReadData } /* 0x102a */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x191d_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x191d_ReadData } /* 0x191d */, 
  {  9, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x1921_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x1921_ReadData } /* 0x1921 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2001_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2001_ReadData } /* 0x2001 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2002_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2002_ReadData } /* 0x2002 */, 
  {  8, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2003_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2003_ReadData } /* 0x2003 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2008_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2008_ReadData } /* 0x2008 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x200a_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x200a_ReadData } /* 0x200a */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x200b_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x200b_ReadData } /* 0x200b */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x200c_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x200c_ReadData } /* 0x200c */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2010_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2010_ReadData } /* 0x2010 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2014_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2014_ReadData } /* 0x2014 */, 
  {  6, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x2024_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x2024_ReadData } /* 0x2024 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x292e_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x292e_ReadData } /* 0x292e */, 
  {  7, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf100_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf100_ReadData } /* 0xf100 */, 
  {  0, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf10b_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Rte_Call_DidServices_0xf10b_ReadDataLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf10b_ReadData } /* 0xf10b */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf10d_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf10d_ReadData } /* 0xf10d */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf154_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf154_ReadData } /* 0xf154 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf155_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf155_ReadData } /* 0xf155 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf158_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf158_ReadData } /* 0xf158 */, 
  { 14, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf180_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf180_ReadData } /* 0xf180 */, 
  { 14, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf181_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf181_ReadData } /* 0xf181 */, 
  { 14, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf182_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf182_ReadData } /* 0xf182 */, 
  { 15, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf183_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf183_ReadData } /* 0xf183 */, 
  { 15, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf184_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf184_ReadData } /* 0xf184 */, 
  { 15, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf185_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf185_ReadData } /* 0xf185 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf186_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf186_ReadData } /* 0xf186 */, 
  { 11, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf187_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf187_ReadData } /* 0xf187 */, 
  { 11, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf188_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf188_ReadData } /* 0xf188 */, 
  { 15, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf18c_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf18c_ReadData } /* 0xf18c */, 
  { 11, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf191_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf191_ReadData } /* 0xf191 */, 
  { 11, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf192_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf192_ReadData } /* 0xf192 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf193_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf193_ReadData } /* 0xf193 */, 
  { 11, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf194_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf194_ReadData } /* 0xf194 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf195_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf195_ReadData } /* 0xf195 */, 
  { 67, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf1a0_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf1a0_ReadData } /* 0xf1a0 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Dcm_22_DummyCheckCondition, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Dcm_DspCall_DidServices_0xf1a2_ReadData } /* 0xf1a2 */, 
  {  6, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf1a3_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf1a3_ReadData } /* 0xf1a3 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf1a4_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf1a4_ReadData } /* 0xf1a4 */, 
  { 322, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd01_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd01_ReadData } /* 0xfd01 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd02_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd02_ReadData } /* 0xfd02 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd03_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd03_ReadData } /* 0xfd03 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd07_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd07_ReadData } /* 0xfd07 */, 
  {  8, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd0e_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd0e_ReadData } /* 0xfd0e */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd10_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd10_ReadData } /* 0xfd10 */, 
  { 28, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd12_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd12_ReadData } /* 0xfd12 */, 
  { 75, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd13_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd13_ReadData } /* 0xfd13 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd14_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd14_ReadData } /* 0xfd14 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd17_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd17_ReadData } /* 0xfd17 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd19_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd19_ReadData } /* 0xfd19 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1a_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1a_ReadData } /* 0xfd1a */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1b_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1b_ReadData } /* 0xfd1b */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1c_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1c_ReadData } /* 0xfd1c */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1e_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1e_ReadData } /* 0xfd1e */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd20_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd20_ReadData } /* 0xfd20 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd21_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd21_ReadData } /* 0xfd21 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd23_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd23_ReadData } /* 0xfd23 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd25_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd25_ReadData } /* 0xfd25 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd26_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd26_ReadData } /* 0xfd26 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd27_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd27_ReadData } /* 0xfd27 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd29_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd29_ReadData } /* 0xfd29 */, 
  {  5, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd30_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd30_ReadData } /* 0xfd30 */, 
  { 12, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd31_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd31_ReadData } /* 0xfd31 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda1_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda1_ReadData } /* 0xfda1 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda2_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda2_ReadData } /* 0xfda2 */, 
  { 12, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda3_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda3_ReadData } /* 0xfda3 */, 
  { 64, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdac_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdac_ReadData } /* 0xfdac */, 
  {  7, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdad_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdad_ReadData } /* 0xfdad */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdae_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdae_ReadData } /* 0xfdae */, 
  { 176, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdaf_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdaf_ReadData } /* 0xfdaf */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb0_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb0_ReadData } /* 0xfdb0 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb1_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb1_ReadData } /* 0xfdb1 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb2_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb2_ReadData } /* 0xfdb2 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb3_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb3_ReadData } /* 0xfdb3 */, 
  {  8, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb4_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb4_ReadData } /* 0xfdb4 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb5_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb5_ReadData } /* 0xfdb5 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb6_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb6_ReadData } /* 0xfdb6 */, 
  { 18, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb7_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb7_ReadData } /* 0xfdb7 */
};
/* Security access property table. */
CONST(Dcm_SecAccessTableType, DCM_CONST) dcm27_ServiceInfoTable[1] = 
{
  { 2, 4, 4, 0, 2, 2, 5, 6, 1000, 0, (Dcm_RteGetSeedCallBackType)Rte_Call_SecurityAccess_1_GetSeed, (Dcm_RteSendKeyCallBackType)Rte_Call_SecurityAccess_1_CompareKey } /* SubFuncId: 0x01 */
};
/* Service 0x28 sub-func state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm28_StateInfoTable[2] = 
{
   3,  3
};
CONST(Dcm_28_RtePermCallBackType, DCM_CONST) dcm28_ComControlPermFunc = Rte_Call_ComControlService_CheckCondition;
/* Service 0x2E DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2E_DidStateInfoTable[34] = 
{
   3 /* DID: 0x0100 */, 
   1 /* DID: 0x2023 */, 
   6 /* DID: 0xf183 */, 
   6 /* DID: 0xf184 */, 
   6 /* DID: 0xf185 */, 
   5 /* DID: 0xf187 */, 
   0 /* DID: 0xf18c */, 
   0 /* DID: 0xfd02 */, 
   0 /* DID: 0xfd03 */, 
   0 /* DID: 0xfd07 */, 
   0 /* DID: 0xfd12 */, 
   0 /* DID: 0xfd19 */, 
   0 /* DID: 0xfd1b */, 
   0 /* DID: 0xfd1e */, 
   0 /* DID: 0xfd21 */, 
   0 /* DID: 0xfd23 */, 
   0 /* DID: 0xfd25 */, 
   0 /* DID: 0xfd26 */, 
   0 /* DID: 0xfd27 */, 
   0 /* DID: 0xfd29 */, 
   0 /* DID: 0xfd30 */, 
   0 /* DID: 0xfda1 */, 
   0 /* DID: 0xfda2 */, 
   0 /* DID: 0xfda3 */, 
   0 /* DID: 0xfdac */, 
   0 /* DID: 0xfdae */, 
   0 /* DID: 0xfdb0 */, 
   0 /* DID: 0xfdb1 */, 
   0 /* DID: 0xfdb2 */, 
   0 /* DID: 0xfdb3 */, 
   0 /* DID: 0xfdb4 */, 
   0 /* DID: 0xfdb5 */, 
   0 /* DID: 0xfdb6 */, 
   0 /* DID: 0xfdb7 */
};
/* Service 0x2E DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm2E_DidHandleTable[35] = 
{
   34 /* Total size of the lookup table */, 
    0 /* DID: 0x0100 */, 
   24 /* DID: 0x2023 */, 
   39 /* DID: 0xf183 */, 
   40 /* DID: 0xf184 */, 
   41 /* DID: 0xf185 */, 
   43 /* DID: 0xf187 */, 
   45 /* DID: 0xf18c */, 
   56 /* DID: 0xfd02 */, 
   57 /* DID: 0xfd03 */, 
   58 /* DID: 0xfd07 */, 
   63 /* DID: 0xfd12 */, 
   67 /* DID: 0xfd19 */, 
   69 /* DID: 0xfd1b */, 
   71 /* DID: 0xfd1e */, 
   73 /* DID: 0xfd21 */, 
   74 /* DID: 0xfd23 */, 
   75 /* DID: 0xfd25 */, 
   76 /* DID: 0xfd26 */, 
   77 /* DID: 0xfd27 */, 
   78 /* DID: 0xfd29 */, 
   79 /* DID: 0xfd30 */, 
   81 /* DID: 0xfda1 */, 
   82 /* DID: 0xfda2 */, 
   83 /* DID: 0xfda3 */, 
   84 /* DID: 0xfdac */, 
   86 /* DID: 0xfdae */, 
   88 /* DID: 0xfdb0 */, 
   89 /* DID: 0xfdb1 */, 
   90 /* DID: 0xfdb2 */, 
   91 /* DID: 0xfdb3 */, 
   92 /* DID: 0xfdb4 */, 
   93 /* DID: 0xfdb5 */, 
   94 /* DID: 0xfdb6 */, 
   95 /* DID: 0xfdb7 */
};
/* Service 0x2E DID property table */
CONST(Dcm_2E_ServiceInfoType, DCM_CONST) dcm2E_ServiceInfoTable[34] = 
{
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0x0100_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0x0100_WriteData } /* 0x0100 */, 
  { 50, 255, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0x2023_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0x2023_WriteData } /* 0x2023 */, 
  { 15, 15, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf183_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf183_WriteData } /* 0xf183 */, 
  { 15, 15, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf184_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf184_WriteData } /* 0xf184 */, 
  { 15, 15, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf185_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf185_WriteData } /* 0xf185 */, 
  { 11, 11, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf187_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf187_WriteData } /* 0xf187 */, 
  { 15, 15, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf18c_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf18c_WriteData } /* 0xf18c */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd02_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd02_WriteData } /* 0xfd02 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd03_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd03_WriteData } /* 0xfd03 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd07_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd07_WriteData } /* 0xfd07 */, 
  { 28, 28, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd12_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd12_WriteData } /* 0xfd12 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd19_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd19_WriteData } /* 0xfd19 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd1b_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd1b_WriteData } /* 0xfd1b */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd1e_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd1e_WriteData } /* 0xfd1e */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd21_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd21_WriteData } /* 0xfd21 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd23_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd23_WriteData } /* 0xfd23 */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd25_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd25_WriteData } /* 0xfd25 */, 
  {  3,  3, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd26_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd26_WriteData } /* 0xfd26 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd27_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd27_WriteData } /* 0xfd27 */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd29_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd29_WriteData } /* 0xfd29 */, 
  {  5,  5, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd30_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd30_WriteData } /* 0xfd30 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda1_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda1_WriteData } /* 0xfda1 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda2_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda2_WriteData } /* 0xfda2 */, 
  { 12, 12, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda3_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda3_WriteData } /* 0xfda3 */, 
  { 64, 64, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdac_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdac_WriteData } /* 0xfdac */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdae_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdae_WriteData } /* 0xfdae */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb0_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb0_WriteData } /* 0xfdb0 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb1_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb1_WriteData } /* 0xfdb1 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb2_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb2_WriteData } /* 0xfdb2 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb3_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb3_WriteData } /* 0xfdb3 */, 
  {  8,  8, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb4_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb4_WriteData } /* 0xfdb4 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb5_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb5_WriteData } /* 0xfdb5 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb6_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb6_WriteData } /* 0xfdb6 */, 
  { 18, 18, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb7_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb7_WriteData } /* 0xfdb7 */
};
/* Service 0x2F DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2F_DidStateInfoTable[5] = 
{
   1 /* DID: 0x5051 */, 
   1 /* DID: 0x5052 */, 
   1 /* DID: 0x5aab */, 
   0 /* DID: 0xfd0d */, 
   0 /* DID: 0xfd11 */
};
/* Service 0x2F DID and ControlOp state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2F_SubFuncStateInfoTable[12] = 
{
   1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0
};
/* Service 0x2F DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm2F_DidHandleTable[6] = 
{
    5 /* Total size of the lookup table */, 
   27 /* DID: 0x5051 */, 
   28 /* DID: 0x5052 */, 
   29 /* DID: 0x5aab */, 
   59 /* DID: 0xfd0d */, 
   62 /* DID: 0xfd11 */
};
/* Service 0x2F DID property table */
CONST(Dcm_2F_ServiceInfoType, DCM_CONST) dcm2F_ServiceInfoTable[12] = 
{
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5051_ReturnControlToECU } /* DID: 0x5051 */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5051_ResetToDefault } /* DID: 0x5051 */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5051_ShortTermAdjustment } /* DID: 0x5051 */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5052_ReturnControlToECU } /* DID: 0x5052 */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5052_ShortTermAdjustment } /* DID: 0x5052 */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5aab_ReturnControlToECU } /* DID: 0x5aab */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5aab_ResetToDefault } /* DID: 0x5aab */, 
  {  1,  1,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0x5aab_ShortTermAdjustment } /* DID: 0x5aab */, 

  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd0d_ReturnControlToECU } /* DID: 0xfd0d */, 
  {  2,  2,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd0d_ShortTermAdjustment } /* DID: 0xfd0d */, 
  {  0,  0,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd11_ReturnControlToECU } /* DID: 0xfd11 */, 
  {  2,  2,  0, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd11_ShortTermAdjustment } /* DID: 0xfd11 */
};
/* Table of 0x2F DID to sub-function mapping. */
CONST(Dcm_2F_MemInstHandleType, DCM_CONST) dcm2F_DidControlTypeInfo[5][3] = 
{
  {    0,    1,    2 } /* DID: 0x5051 */, 
  {    3,   12,    4 } /* DID: 0x5052 */, 
  {    5,    6,    7 } /* DID: 0x5aab */, 
  {    8,   12,    9 } /* DID: 0xfd0d */, 
  {   10,   12,   11 } /* DID: 0xfd11 */
};
/* Service 0x31 RID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm31_RidStateInfoTable[12] = 
{
   3 /* RID: 0x0200 */, 
   0 /* RID: 0xd001 */, 
   1 /* RID: 0xd002 */, 
   0 /* RID: 0xf000 */, 
   0 /* RID: 0xf001 */, 
   0 /* RID: 0xf003 */, 
   0 /* RID: 0xf004 */, 
   0 /* RID: 0xf005 */, 
   0 /* RID: 0xf008 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf0ff */, 
   3 /* RID: 0xfee0 */
};
/* Service 0x31 RID and ControlOp state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm31_SubFuncStateInfoTable[16] = 
{
   3 /* RID: 0x0200 */, 
   3 /* RID: 0x0200 */, 
   3 /* RID: 0xd001 */, 
   0 /* RID: 0xd001 */, 
   1 /* RID: 0xd002 */, 
   0 /* RID: 0xf000 */, 
   0 /* RID: 0xf001 */, 
   0 /* RID: 0xf003 */, 
   0 /* RID: 0xf004 */, 
   0 /* RID: 0xf005 */, 
   0 /* RID: 0xf008 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf0ff */, 
   3 /* RID: 0xfee0 */
};
/* Service 0x31 RID property table */
CONST(Dcm_31_ServiceInfoType, DCM_CONST) dcm31_ServiceInfoTable[16] = 
{
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0x0200_Start } /* RID: 0x0200 */, 
  {  0,  0,  1, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0x0200_RequestResults } /* RID: 0x0200 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xd001_Start } /* RID: 0xd001 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xd001_Stop } /* RID: 0xd001 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xd002_Start } /* RID: 0xd002 */, 
  {  3,  3,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf000_Start } /* RID: 0xf000 */, 
  {  2,  2,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf001_Start } /* RID: 0xf001 */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf003_Start } /* RID: 0xf003 */, 

  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf004_Start } /* RID: 0xf004 */, 
  {  2,  2,  3, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf005_Start } /* RID: 0xf005 */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf008_Start } /* RID: 0xf008 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_Start } /* RID: 0xf009 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_Stop } /* RID: 0xf009 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_RequestResults } /* RID: 0xf009 */, 
  {  6,  6,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf0ff_Start } /* RID: 0xf0ff */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xfee0_Start } /* RID: 0xfee0 */
};
/* Table of 0x31 RID to sub-function mapping. */
CONST(Dcm_MemRidInstHandleType, DCM_CONST) dcm31_ControlTypeInfo[12][3] = 
{
  {    0,   16,    1 } /* RID: 0x0200 */, 
  {    2,    3,   16 } /* RID: 0xd001 */, 
  {    4,   16,   16 } /* RID: 0xd002 */, 
  {    5,   16,   16 } /* RID: 0xf000 */, 
  {    6,   16,   16 } /* RID: 0xf001 */, 
  {    7,   16,   16 } /* RID: 0xf003 */, 
  {    8,   16,   16 } /* RID: 0xf004 */, 
  {    9,   16,   16 } /* RID: 0xf005 */, 

  {   10,   16,   16 } /* RID: 0xf008 */, 
  {   11,   12,   13 } /* RID: 0xf009 */, 
  {   14,   16,   16 } /* RID: 0xf0ff */, 
  {   15,   16,   16 } /* RID: 0xfee0 */
};
/* Control DTC Setting state filter table. */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm85_StateInfoTable[2] = 
{
  4, 4
};
#define DCM_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Internal implementation
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

STATIC FUNC(void, DCM_CODE) DcmOnTimeoutDummyCallBack(Dcm_TimerIdType timerId)
{
  DCM_IGNORE_UNREF_PARAM(timerId); /* PRQA S 3112 */ /* Avoid warnings on specific API implementation */
}


STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyGetLength(Dcm_RteDataLenPtrType resDataLenPtr) /* PRQA S 3673 */ /* AUTOSAR defined interface */
{
  DCM_IGNORE_UNREF_PARAM(resDataLenPtr); /* PRQA S 3112 */ /* Avoid warnings on specific API implementation */
  return DCM_E_NOT_OK;
}


STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyCheckCondition(Dcm_NegativeResponseCodePtrType errorCodePtr) /* PRQA S 3673 */ /* AUTOSAR defined interface */
{
  DCM_IGNORE_UNREF_PARAM(errorCodePtr); /* PRQA S 3112 */ /* Avoid warnings on specific API implementation */
  return DCM_E_OK;
}


STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_DspCall_DidServices_0xf1a2_ReadData(Dcm_RteDataPtrType resData) /* PRQA S 0779 */ /* AUTOSAR naming convention */
{
  Dcm_CopyRom2Ram((*resData),kGENyVersion,10);/* copy the delivery information into the buffer */
  return DCM_E_OK;
}


#define DCM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



