/* -----------------------------------------------------------------------------
  Filename:    Dem_IntEvtId.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-05-29  15:06:42
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_INTEVTID_H)
#define DEM_INTEVTID_H

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define DEM_EVENT_INVALID                    0
#define DTC_0xd95283                         1
#define DTC_0xd93286                         2
#define DTC_0xd01387                         3
#define DTC_0xd01187                         4
#define DTC_0xd01087                         5
#define DTC_0xd00787                         6
#define DTC_0xd00687                         7
#define DTC_0xd00587                         8
#define DTC_0xc4232f                         9
#define DTC_0xc4222f                         10
#define DTC_0xc4152f                         11
#define DTC_0xc4012f                         12
#define DTC_0xc10087                         13
#define DTC_0xc00188                         14
#define DTC_0xc00187                         15
#define DTC_0xa23b05                         16
#define DTC_0xa22c51                         17
#define DTC_0xa1991c                         18
#define DTC_0xa19917                         19
#define DTC_0xa19916                         20
#define DTC_0x621749                         21
#define DTC_0x621748                         22
#define DTC_0x621098                         23
#define DTC_0x621068                         24
#define DTC_0x620525                         25
#define DTC_0x559349                         26
#define DTC_0x559313                         27
#define DTC_0x559312                         28
#define DTC_0x559311                         29
#define DTC_0x559219                         30
#define DTC_0x559213                         31
#define DTC_0x559212                         32
#define DTC_0x559211                         33
#define DTC_0x559201                         34
#define DTC_0x521a54                         35
#define DTC_0x52192f                         36
#define DTC_0x500909                         37
#define DTC_0x500568                         38
#define DTC_0x500386                         39


#endif /* DEM_INTEVTID_H */
