/* -----------------------------------------------------------------------------
  Filename:    Dem_Lcfg.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\Synergy\EA3\Working\Fiasa_326_327\Fiasa_326_327_03.01.00\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-10-29  10:48:19
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_LCFG_H)
#define DEM_LCFG_H

/* -----------------------------------------------------------------------------
    &&&~ Dem Parameters
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_MAX_NUMBER_EVENT_ENTRY           10
#define DEM_NUMBER_OF_VIEWS                  0
#define DEM_NUMBER_OF_EVENTS                 62
#define DEM_STATUS_AVAILABILITY_MASK         0xFFu
#define DEM_NUMBER_OF_OPERATION_CYCLES       4
#define DEM_NUMBER_OF_INDICATORS             0
#define DEM_MAX_EXTDATA_RECORD_SIZE          1
#define DEM_MAX_SNAPSHOT_RECORD_SIZE         15
#define DEM_BSW_ERROR_BUFFER_SIZE            30
#define DEM_ADD_ERROR_BUFFER_SIZE            1
#define DEM_SNAPSHOTS_PER_DTC                2
#define DEM_FIRST_SNAPSHOT_TO_OVERWRITE      1
#define DEM_PRESTORE_FF_BUFFER_SIZE          1
#define DEM_FIRST_EXT_DATA_RECNUM            1
/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Dem configuration type definitions
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
typedef P2VAR(uint8, TYPEDEF, DEM_APPL_DATA) Dem_ApplBufferPtrType; /* PRQA S 0850 */ /* MD_MSR_19.8 */
typedef VAR(uint8, TYPEDEF) Dem_Mem_PrimaryIndexType; /* PRQA S 0850 */ /* MD_MSR_19.8 */
typedef struct Dem_NvAdminDataTypeTag
{
  uint32 activeVersion;
  uint16 cycleCounter[DEM_NUMBER_OF_OPERATION_CYCLES];
} Dem_NvAdminDataType;
typedef struct Dem_NvStatusDataTypeTag
{
  uint8 eventStatus[DEM_NUMBER_OF_EVENTS + 1];
  Dem_EventIdType firstFailedEvent;
  Dem_EventIdType firstConfirmedEvent;
  Dem_EventIdType mostRecentFailedEvent;
  Dem_EventIdType mostRecentConfirmedEvent;
} Dem_NvStatusDataType;
typedef VAR(uint8, TYPEDEF) Dem_NvPrimaryEntryType[2 + 4 + 2 + DEM_MAX_EXTDATA_RECORD_SIZE + (DEM_SNAPSHOTS_PER_DTC*DEM_MAX_SNAPSHOT_RECORD_SIZE) + 1];
typedef struct Dem_DemConfigurationTypeTag
{
  uint8 DTCTranslationFormat;
} Dem_DemConfigurationType;
typedef struct Dem_DIDLookupTableTypeTag
{
  uint16 did;
  Dem_GetDataValueByDataIdentifierType pFunc;
} Dem_DIDLookupTableType;
typedef VAR(uint8, TYPEDEF) Dem_DataRecordSizeType; /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Global Data Prototypes
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ RAM buffers of NVRAM stored data
 ----------------------------------------------------------------------------- */

#define DEM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern VAR(Dem_NvAdminDataType, DEM_APPL_DATA) Dem_Cfg_NvAdminData; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvStatusDataType, DEM_APPL_DATA) Dem_Cfg_NvEventStatusData; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_1; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_2; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_3; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_4; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_5; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_6; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_7; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_8; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_9; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_10; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(uint8, DEM_APPL_DATA) Dem_PreFFBuffer[DEM_PRESTORE_FF_BUFFER_SIZE]; /* PRQA S 0850 */ /* MD_MSR_19.8 */

#define DEM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ RAM buffers for internal data
 ----------------------------------------------------------------------------- */

#define DEM_START_SEC_VAR_FAST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern VAR(Dem_NvPrimaryEntryType, DEM_APPL_DATA) Dem_Cfg_NvPrimaryEntry_0; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern volatile VAR(Dem_DtcInternalStatusType, DEM_VAR_NOINIT_FAST) Dem_DtcInternalStatus[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_MSR_8.12 */
extern VAR(sint8, DEM_VAR_NOINIT_FAST) Dem_DtcFaultDetectionCounter[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern VAR(uint8, DEM_VAR_NOINIT_FAST) Dem_Mem_PrimaryEntryStatus[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern VAR(Dem_Mem_PrimaryIndexType, DEM_VAR_NOINIT_FAST) Dem_Mem_PrimaryChronology[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern VAR(uint8, DEM_VAR_NOINIT_FAST) Dem_Mem_AgingCounter[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */

#define DEM_STOP_SEC_VAR_FAST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define DEM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern VAR(Dem_OperationCycleStateType, DEM_VAR_NOINIT) Dem_OperationCycleState[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
#define DEM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define DEM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern VAR(uint32, DEM_VAR_NOINIT) Dem_EnableConditionState; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_AQElementType, DEM_VAR_NOINIT) Dem_ActionQueue[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern VAR(Dem_TimeBasedDebounceTimerType, DEM_VAR_NOINIT) Dem_DebounceTimer; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern VAR(Dem_TimeBasedDebounceTimerType, DEM_VAR_NOINIT) Dem_DebounceTimerSlots[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */

#define DEM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Precompile/Linktime specific config data
 ----------------------------------------------------------------------------- */

#define DEM_START_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern CONST(Dem_DemConfigurationType, DEM_CONST) Dem_DemConfiguration; /* PRQA S 0850 */ /* MD_MSR_19.8 */

extern CONST(Dem_NvMBlockIdType, DEM_CONST) Dem_Cfg_NvAdminBlock; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(Dem_NvMBlockIdType, DEM_CONST) Dem_Cfg_NvEventStatusBlock; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(Dem_NvMBlockIdType, DEM_CONST) Dem_Cfg_NvPrimaryBlocks[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */

extern CONST(Dem_NvPrimaryEntryType, DEM_CONST) Dem_Cfg_NvPrimaryEntry_Zero; /* PRQA S 0850 */ /* MD_MSR_19.8 */

extern CONST(Dem_DTCGroupMappingType, DEM_CONST) Dem_DTCGroupTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_CONST) Dem_LinkTimeProperty[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_CONST) Dem_InitMonitorIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_InitMonitorFPtrType, DEM_CONST) Dem_InitMonitorFPtrTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_TriggerDTCFunctionType, DEM_CONST) Dem_TriggerDTCFunctionTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_TriggerFunctionType, DEM_CONST) Dem_TriggerFunctionTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_DTCGroupKindType, DEM_CONST) Dem_EventGroupTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_DIDLookupTableType, DEM_CONST) Dem_DIDLookupTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_GetExtDataRecordFPtrType, DEM_CONST) Dem_GetExtDataRecordListTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_CONST) Dem_ClearAllowedIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_ClearAllowedFPtrType, DEM_CONST) Dem_ClearAllowedFPtrTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */


extern CONST(uint8, DEM_CONST) Dem_StatusAvailabilityMask; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_MaxSizeOfSnapshotRecord; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_MaxSizeOfExtdataRecord; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_NumberOfOperationCycles; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_NumberOfIndicators; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(Dem_EventIdType, DEM_CONST) Dem_Cfg_MaxEventId; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(Dem_Mem_PrimaryIndexType, DEM_CONST) Dem_Cfg_NumPrimaryEntries; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_SizeofPreFFBuffer; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint8, DEM_CONST) Dem_SnapshotsPerDTC; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint8, DEM_CONST) Dem_FirstOverwritableSnapshot; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint8, DEM_CONST) Dem_ReportErrorBufferSize; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_ActionQueueCount; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint8, DEM_CONST) Dem_DTCGroupMappingCount; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint8, DEM_CONST) Dem_SizeofEventIdType; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONST(uint16, DEM_CONST) Dem_NumberOfDebounceTimerSlots; /* PRQA S 0850 */ /* MD_MSR_19.8 */

extern CONSTP2VAR(uint32, DEM_CONST, DEM_APPL_DATA) Dem_Cfg_AdminActiveVersionPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(uint16, DEM_CONST, DEM_APPL_DATA) Dem_Cfg_AdminCycleCounterPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(uint8, DEM_CONST, DEM_VAR_NOINIT) Dem_Cfg_AdminCycleStatePtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */

extern volatile CONSTP2VAR(uint8, DEM_CONST, DEM_APPL_DATA) Dem_EventStatusPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */

extern CONSTP2VAR(sint8, DEM_CONST, DEM_VAR_NOINIT_FAST) Dem_FaultDetectionCounterPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_FirstFailedEventIdPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_FirstConfirmedEventIdPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_MostRecentFailedEventIdPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(Dem_EventIdType, DEM_CONST, DEM_APPL_DATA) Dem_MostRecentConfmdEventIdPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(uint8, DEM_CONST, DEM_VAR_NOINIT_FAST) Dem_DtcAgingCounterPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern CONSTP2VAR(Dem_NvPrimaryEntryType, DEM_CONST, DEM_APPL_DATA) Dem_Cfg_PrimaryStackPtr[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONSTP2VAR(Dem_NvPrimaryEntryType, DEM_CONST, DEM_VAR_NOINIT) Dem_Cfg_NvCommitEntryPtr; /* PRQA S 0850 */ /* MD_MSR_19.8 */



#define DEM_STOP_SEC_CONST_LCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Global Function Prototypes
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Diag_AsrDemLinktimeCRC */
#define DEM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Access function to global configuration data
 ----------------------------------------------------------------------------- */

extern FUNC(Dem_EventIdType, DEM_CODE) Dem_Cfg_GetMaxEventId(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_GetDTCTranslationFormat(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint16, DEM_CODE) DemCfg_GetMaxCountOfOperationCycle(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_GetCountOfSnapshotsPerDTC(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_GetFirstOccurredRecordNr(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint16, DEM_CODE) DemCfg_GetMaxSnapshotRecordSize(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_Get1stOverwrtSnapshotIndex(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* No longer used, kept for compatibility */
#define DemCfg_GetCountOfGlobalSsDIDs(EventId) 0
#define DemCfg_GetFirstGlobalSsRecord(EventId) 0
extern FUNC(uint16, DEM_CODE) DemCfg_GetMaxExtdataRecordSize(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(Dem_Mem_PrimaryIndexType, DEM_CODE) Dem_Cfg_GetNumPrimaryEntries(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint32, DEM_CODE) DemCfg_GetEnableConditionInitValue(void); /* PRQA S 0850 */ /* MD_MSR_19.8 */


extern FUNC(Dem_DTCGroupKindType, DEM_CODE) Dem_MapGroupNumberToGroupKind(Dem_DTCType DTCGroupNumber); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(Dem_DTCType, DEM_CODE) DemCfg_GetDTCnumber(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */

/* -----------------------------------------------------------------------------
    &&&~ Access functions to the event specific configurable data
 ----------------------------------------------------------------------------- */

extern FUNC(Dem_InitMonitorFPtrType, DEM_CODE) DemCfg_GetInitMonitorFPtr(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* Map EventId to the first Index into the list of TriggerOnDTCStatusChanged callbacks. */
#define DemCfg_GetFirstTriggerOnDTC(EventId) 0
/* Map EventId to the number of corresponding TriggerOnDTCStatusChanged callbacks. */
#define DemCfg_GetCountOfTriggerOnDTC(EventId) 0
/* Map EventId to the first Index into the list of TriggerOnEventStatusChanged callbacks. */
#define DemCfg_GetFirstTriggerOnEvent(EventId) 0
/* Map EventId to number of TriggerOnEventStatusChanged callbacks. */
#define DemCfg_GetCountOfTriggerOnEvent(EventId) 0
/* Map EventId to priority. */
#define DemCfg_GetEventPriority(EventId)     0
/* Map EventId to severity. */
#define DemCfg_GetDTCSeverity(EventId)       (Dem_DTCSeverityTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to its operation cycle. See Dem_Types.h for healing cycle IDs. */
#define DemCfg_GetOperationCycleId(EventId)  0
/* Map EventId to its aging cycle. See Dem_Types.h for aging cycle IDs. */
#define DemCfg_GetAgingCycleId(EventId)      0
/* Map EventId to its indicator healing cycle. See Dem_Types.h for operation cycle IDs. */
#define DemCfg_GetIndHealingCycleId(EventId) 0
/* Maps EventId to <Number of Aging Cycles> */
#define DemCfg_GetNumberOfAgingCycles(EventId) 40
/* Map EventId to relevant enable conditions. Set bit means enable condition must be active for the Event. */
#define DemCfg_GetEnableConditionMask(EventId) 0
/* Map EventId to the number of relevant indicators. */
#define DemCfg_GetCountOfIndicatorIds(EventId) 0
/* Map IndIdIdx to IndicatorId. Sum up DemCfg_GetCountOfIndicatorIds(0) .. DemCfg_GetCountOfIndicatorIds(EventID-1) to get first index for EventId. */
#define DemCfg_GetIndicatorId(IndIdIdx)      0
/* Map IndIdIdx to indicator status. Sum up DemCfg_GetCountOfIndicatorIds(0) .. DemCfg_GetCountOfIndicatorIds(EventID-1) to get first index for EventId. */
#define DemCfg_GetIndicatorStatusType(IndIdIdx) 0
/* Map EventId to a ViewID. */
#define DemCfg_GetViewId(EventId)            255
/* Map EventId to functional unit. */
#define DemCfg_GetFunctionalUnit(EventId)    (Dem_FunctionalUnitTable[Dem_PostBuildProperty[EventId]])
extern FUNC(boolean, DEM_CODE) DemCfg_GetDtcSupportWarningIndicator(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* Map EventId to flag value. */
#define DemCfg_GetDtcSuppressFlag(EventId)   FALSE
extern FUNC(boolean, DEM_CODE) DemCfg_GetIsAgingAllowed(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* Test if EventId uses Jump-Up-to-Zero, used for counter based debouncing. */
#define DemCfg_GetIsPredebJumpPreFailed(EventId) 1
/* Test if EventId uses Jump-Down-to-Zero, used for counter based debouncing. */
#define DemCfg_GetIsPredebJumpPrePassed(EventId) 1
extern FUNC(uint8, DEM_CODE) DemCfg_GetPredebStepsizePreFailed(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_GetPredebStepsizePrePassed(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
extern FUNC(uint8, DEM_CODE) DemCfg_GetIsEventTimeBasedDebounce(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */
/* Map EventId to 'prefailed' qualification time. Used for timer based debouncing. */
#define DemCfg_GetTimeBasedDebValueFailed(EventId) (Dem_DebounceFailedTimeTable[Dem_DebounceIndexTable[Dem_PostBuildProperty[EventId]]])
/* Map EventId to 'prepassed' qualification time. Used for timer based debouncing. */
#define DemCfg_GetTimeBasedDebValuePassed(EventId) (Dem_DebouncePassedTimeTable[Dem_DebounceIndexTable[Dem_PostBuildProperty[EventId]]])
/* Map time slot index to EventId. Used for timer based debouncing. */
#define DemCfg_GetTimeBasedDebounceTableIdx(EventId) (Dem_EventIdToTimeBasedDebIdxTable[EventId])
/* Map EventId to time slot index. Used for timer based debouncing. */
#define DemCfg_GetEventIdFromTimeBasedDebounceTableIdx(TimeBasedIdx) (Dem_TimeBasedDebIdxToEventIdTable[TimeBasedIdx])
/* Map EventId to DTC kind. Dem_DTCKindType is defined in dem_types.h */
#define DemCfg_GetDTCKind(EventId)           (Dem_DtcKindTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to supported origin (bitcoded). Primary == 0x02, Mirror == 0x04, Permanent == 0x08, Secondary == 0x10. */
#define DemCfg_GetDTCOrigin(EventId)         (Dem_EventDestinationTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to DTC group index. Internal event == 0x00, OBD == 0x01, P == 0x02, C == 0x04, B == 0x08, U == 0x10, ALL == 0xFF */
#define DemCfg_GetDTCGroupKind(EventId)      (Dem_EventGroupTable[Dem_LinkTimeProperty[EventId]])
/* Map EventId to the Index of the first DID of its snapshot records. */
#define DemCfg_GetFirstSnapshot(EventId)     (Dem_EventDidIndexTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to the total number of DIDs across all of its snapshot records. */
#define DemCfg_GetCountOfSnapshotDIDs(EventId) (Dem_EventDidCountTable[Dem_PostBuildProperty[EventId]])
/* Map SsRecIdx to the DID number. Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
#define DemCfg_GetSnapshotDID(SsRecIdx)      (Dem_DidNumberTable[SsRecIdx])
/* Map SsRecIdx to a list of DID numbers. Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
#define DemCfg_GetSnapshotDIDAddr(SsRecIdx)  ( & Dem_DidNumberTable[SsRecIdx])
/* Map SsRecIdx to the size of the DID (in byte). Get first SsRecIdx either per Event using DemCfg_GetFirstSnapshot(EventId) or per Snapshot by DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) */
#define DemCfg_GetSnapshotDIDDataSize(SsRecIdx) (Dem_DidSizeTable[SsRecIdx])
/* Map EventId to first Index into snapshot table. */
#define DemCfg_GetFirstSnapshotRecNumber(EventId) (Dem_SnapshotIndexTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to number of snapshot records. */
#define DemCfg_GetCountOfSnapshotRecNumbers(EventId) (Dem_SnapshotCountTable[Dem_PostBuildProperty[EventId]])
/* Map ssRecordIndex to number of the snapshot record. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
#define DemCfg_GetSnapshotRecordNumber(ssRecordIndex) (Dem_SnapshotNumberTable[ssRecordIndex])
/* Map ssRecordIndex to the size of the snapshot record (in byte). The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
#define DemCfg_GetSnapshotRecordDIDsSize(ssRecordIndex) (Dem_SnapshotSizeTable[ssRecordIndex])
/* Map ssRecordIndex to the number of DIDs in the snapshot record. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
#define DemCfg_GetSnapshotRecordNumberOfDIDs(ssRecordIndex) (Dem_SnapshotDidCountTable[ssRecordIndex])
/* Map ssRecordIndex to first Index into DID table. The first valid ssRecordIndex is DemCfg_GetFirstSnapshotRecNumber(EvenId). */
#define DemCfg_GetSnapshotRecordDIDIndex(ssRecordIndex) (Dem_SnapshotDidIndexTable[ssRecordIndex])
/* Map EventId to the offset into the prestored snapshot buffer. */
#define DemCfg_PrestoreFFBufStartOffset(EventId) 0
/* Map EventId to size of its prestored snapshot data. */
#define DemCfg_PrestoreFFBufSize(EventId)    0
/* Map EventId to the end offset into the prestored snapshot buffer. */
#define DemCfg_PrestoreFFBufEndOffset(EventId) 0
/* Map EventId to Index of first Extended Data Record. Index is valid in Dem_Record* tables. */
#define DemCfg_GetFirstExtendedRecord(EventId) (Dem_EventRecordIndexTable[Dem_PostBuildProperty[EventId]])
/* Map EventId to number of Extended Data Records. */
#define DemCfg_GetCountOfCurrentExtendedRecord(EventId) (Dem_EventRecordSizeTable[Dem_PostBuildProperty[EventId]])
/* Map ExtRecIdx to RecordId of an Extended Data Record. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
#define DemCfg_GetExtendedRecordNumber(ExtRecIdx) (Dem_RecordIdTable[ExtRecIdx])
/* Map ExtRecIdx to size [byte] of an Extended Data Record. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
#define DemCfg_GetExtendedRecordNumberDataSize(ExtRecIdx) (Dem_RecordSizeTable[ExtRecIdx])
/* Map ExtRecIdx to size [byte] of an Extended Data Record, in MirrorMemory. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
#define DemCfg_GetMirExtendedRecordNumberDataSize(ExtRecIdx) 0
/* Map ExtRecIdx to function pointer used to get the data. (First) valid ExtRecIdx per EventId is returned by DemCfg_GetFirstExtendedRecord. */
#define DemCfg_GetExtendedRecordFuncRef(ExtRecIdx) (Dem_RecordFuncTable[ExtRecIdx])
/* Returns if the extended data record supports the warning indicator counter. */
#define DemCfg_IsExtRecWarnCntEnabled()      FALSE
/* Map EventId to valid identity mask. Can be multiple identity (only one bit set) or VSG mode (multiple bits set). */
#define DemCfg_GetEventIdentityVariant(EventId) 0
/* Maps EventId to <Number of Indicator Healing Cycles> */
#define DemCfg_GetNumOfIndHealingCycles(EventId) 0
extern FUNC(Dem_ClearAllowedFPtrType, DEM_CODE) DemCfg_GetClearAllowedFPtr(Dem_EventIdType EventId); /* PRQA S 0850 */ /* MD_MSR_19.8 */



#define DEM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* END of Checksum include for
  - Diag_AsrDemLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Justification of MISRA deviations
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */
/* MD_DEM_8.12:
    Reason:     Prevent compiler optimization based on known array size.
    Risk:       None. The static code is not allowed to access this array directly.
    Prevention: Code inspection. */
/* END of Checksum exclude for
  - Diag_AsrDemLinktimeCRC */



#endif /* DEM_LCFG_H */
