/* -----------------------------------------------------------------------------
  Filename:    Dem_PBcfg.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Dem
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-05-29  15:06:42
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DEM_PBCFG_H)
#define DEM_PBCFG_H

/* -----------------------------------------------------------------------------
    &&&~ Dem configuration type definitions for postbuild
 ----------------------------------------------------------------------------- */



/* -----------------------------------------------------------------------------
    &&&~ Global Data Prototypes
 ----------------------------------------------------------------------------- */

#define DEM_START_SEC_PBCONST
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

extern CONST(uint8, DEM_PBCFG) Dem_PostBuildProperty[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DTCNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DTC_FTB_Table[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_DTCSeverityType, DEM_PBCFG) Dem_DTCSeverityTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_FunctionalUnitTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventFlagsTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DebounceIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DebounceCountInTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DebounceCountOutTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DebounceTypeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DebounceFailedTimeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DebouncePassedTimeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_EventIdType, DEM_PBCFG) Dem_TimeBasedDebIdxToEventIdTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_EventIdToTimeBasedDebIdxTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(Dem_DTCKindType, DEM_PBCFG) Dem_DtcKindTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDestinationTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDidIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventDidCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_DidNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_DidSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotNumberTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotDidIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_SnapshotDidCountTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventRecordIndexTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_EventRecordSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_RecordIdTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint8, DEM_PBCFG) Dem_RecordSizeTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
extern CONST(uint16, DEM_PBCFG) Dem_RecordFuncTable[]; /* PRQA S 0850, 3684 */ /* MD_MSR_19.8, MD_DEM_8.12 */
#define DEM_STOP_SEC_PBCONST
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"





#endif /* DEM_PBCFG_H */
