/* -----------------------------------------------------------------------------
  Filename:    Det_Cfg.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: Det
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-05-29  15:06:42
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(DET_CFG_H)
#define DET_CFG_H

#define DET_ENABLED
#define DETDLL_VERSION                       0x0200u
#define DETDLL_RELEASE_VERSION               0x00u
#ifndef DET_OSTYPE_AUTOSAR
#define DET_OSTYPE_AUTOSAR
#endif


#ifndef DET_USE_DUMMY_FUNCTIONS
#define DET_USE_DUMMY_FUNCTIONS              STD_OFF
#endif


#ifndef DET_USE_DUMMY_STATEMENT
#define DET_USE_DUMMY_STATEMENT              STD_ON
#endif


#ifndef DET_CPU_TMS470
#define DET_CPU_TMS470
#endif


#ifndef DET_PROCESSOR_TI_TMS470_LS30316U
#define DET_PROCESSOR_TI_TMS470_LS30316U
#endif


#ifndef DET_COMP_TI
#define DET_COMP_TI
#endif


#ifndef DET_CRC_CHECK
#define DET_CRC_CHECK                        STD_OFF
#endif


#ifndef DET_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define DET_ATOMIC_BIT_ACCESS_IN_BITFIELD    STD_OFF
#endif


#ifndef DET_ATOMIC_VARIABLE_ACCESS
#define DET_ATOMIC_VARIABLE_ACCESS           32
#endif


#ifndef DET_AUTOSARVERSION
#define DET_AUTOSARVERSION                   3
#endif


#define DET_VERSION_INFO_API                 STD_OFF
#define DET_DEBUG_DISABLED
#define DET_GLOBALFILTERSIZE                 0
#define DET_BREAKFILTERSIZE                  0
#define DET_LOGBUFFERSIZE                    0
#define DET_ENTRY_CALLOUT_DISABLED

#endif /* DET_CFG_H */
