/* -----------------------------------------------------------------------------
  Filename:    PduR_Cfg.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-05-29  15:06:43
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_CFG_H)
#define PDUR_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Generator Version Check
 ----------------------------------------------------------------------------- */

#define GW_ASRPDUR_GENTOOL_GENY_MAJOR_VERSION 0x03u
#define GW_ASRPDUR_GENTOOL_GENY_MINOR_VERSION 0x25u
#define GW_ASRPDUR_GENTOOL_GENY_PATCH_VERSION 0x02u


/* -----------------------------------------------------------------------------
    &&&~ GENy DLL Implementation Version
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Gw_AsrPduRPrecompileCRC */
#define GW_ASRPDUR_DLL_IMPLEMENTATION        (0x14u)
/* END of Checksum include for
  - Gw_AsrPduRPrecompileCRC */


/* START of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */
#ifndef PDUR_OSTYPE_AUTOSAR
#define PDUR_OSTYPE_AUTOSAR
#endif


#ifndef PDUR_USE_DUMMY_FUNCTIONS
#define PDUR_USE_DUMMY_FUNCTIONS             STD_OFF
#endif


#ifndef PDUR_USE_DUMMY_STATEMENT
#define PDUR_USE_DUMMY_STATEMENT             STD_ON
#endif


#ifndef PDUR_CPU_TMS470
#define PDUR_CPU_TMS470
#endif


#ifndef PDUR_PROCESSOR_TI_TMS470_LS30316U
#define PDUR_PROCESSOR_TI_TMS470_LS30316U
#endif


#ifndef PDUR_COMP_TI
#define PDUR_COMP_TI
#endif


#ifndef PDUR_CRC_CHECK
#define PDUR_CRC_CHECK                       STD_OFF
#endif


#ifndef PDUR_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define PDUR_ATOMIC_BIT_ACCESS_IN_BITFIELD   STD_OFF
#endif


#ifndef PDUR_ATOMIC_VARIABLE_ACCESS
#define PDUR_ATOMIC_VARIABLE_ACCESS          32
#endif


#ifndef PDUR_AUTOSARVERSION
#define PDUR_AUTOSARVERSION                  3
#endif


/* END of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ List of Supported PduR Interfaces
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Gw_AsrPduRPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ SUPPORT Switches for each PduR Module Interfaces
 ----------------------------------------------------------------------------- */

#define PDUR_APPLIF_SUPPORT                  STD_OFF
#define PDUR_APPLTP_SUPPORT                  STD_OFF
#define PDUR_CANIF_SUPPORT                   STD_ON
#define PDUR_CANNM_SUPPORT                   STD_OFF
#define PDUR_CANTP_SUPPORT                   STD_ON
#define PDUR_COM_SUPPORT                     STD_ON
#define PDUR_DCM_SUPPORT                     STD_ON
#define PDUR_FRIF_SUPPORT                    STD_OFF
#define PDUR_FRNM_SUPPORT                    STD_OFF
#define PDUR_FRTP_SUPPORT                    STD_OFF
#define PDUR_GW_SUPPORT                      STD_OFF
#define PDUR_INVALID_SUPPORT                 STD_ON
#define PDUR_IPDUM_SUPPORT                   STD_OFF
#define PDUR_J1939TP_SUPPORT                 STD_OFF
#define PDUR_LINIF_SUPPORT                   STD_OFF
#define PDUR_LINTP_SUPPORT                   STD_OFF
#define PDUR_MOSTIF_SUPPORT                  STD_OFF
#define PDUR_MOSTTP_SUPPORT                  STD_OFF
#define PDUR_MULTI_SUPPORT                   STD_OFF
#define PDUR_NMOSEK_SUPPORT                  STD_OFF
#define PDUR_SOAD_SUPPORT                    STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Communication Interfaces Switches for each PduR Module Interfaces
 ----------------------------------------------------------------------------- */

#define PDUR_APPLIF_COMIF                    STD_OFF
#define PDUR_APPLTP_COMIF                    STD_OFF
#define PDUR_CANIF_COMIF                     STD_ON
#define PDUR_CANNM_COMIF                     STD_OFF
#define PDUR_CANTP_COMIF                     STD_OFF
#define PDUR_COM_COMIF                       STD_ON
#define PDUR_DCM_COMIF                       STD_OFF
#define PDUR_FRIF_COMIF                      STD_OFF
#define PDUR_FRNM_COMIF                      STD_OFF
#define PDUR_FRTP_COMIF                      STD_OFF
#define PDUR_GW_COMIF                        STD_OFF
#define PDUR_INVALID_COMIF                   STD_OFF
#define PDUR_IPDUM_COMIF                     STD_OFF
#define PDUR_J1939TP_COMIF                   STD_OFF
#define PDUR_LINIF_COMIF                     STD_OFF
#define PDUR_LINTP_COMIF                     STD_OFF
#define PDUR_MOSTIF_COMIF                    STD_OFF
#define PDUR_MOSTTP_COMIF                    STD_OFF
#define PDUR_MULTI_COMIF                     STD_OFF
#define PDUR_NMOSEK_COMIF                    STD_OFF
#define PDUR_SOAD_COMIF                      STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Transport Protocol Switches for each PduR Module Interfaces
 ----------------------------------------------------------------------------- */

#define PDUR_APPLIF_TP                       STD_OFF
#define PDUR_APPLTP_TP                       STD_OFF
#define PDUR_CANIF_TP                        STD_OFF
#define PDUR_CANNM_TP                        STD_OFF
#define PDUR_CANTP_TP                        STD_ON
#define PDUR_COM_TP                          STD_OFF
#define PDUR_DCM_TP                          STD_ON
#define PDUR_FRIF_TP                         STD_OFF
#define PDUR_FRNM_TP                         STD_OFF
#define PDUR_FRTP_TP                         STD_OFF
#define PDUR_GW_TP                           STD_OFF
#define PDUR_INVALID_TP                      STD_OFF
#define PDUR_IPDUM_TP                        STD_OFF
#define PDUR_J1939TP_TP                      STD_OFF
#define PDUR_LINIF_TP                        STD_OFF
#define PDUR_LINTP_TP                        STD_OFF
#define PDUR_MOSTIF_TP                       STD_OFF
#define PDUR_MOSTTP_TP                       STD_OFF
#define PDUR_MULTI_TP                        STD_OFF
#define PDUR_NMOSEK_TP                       STD_OFF
#define PDUR_SOAD_TP                         STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Transport Protocol Api Switches
 ----------------------------------------------------------------------------- */

#define PDUR_TRANSMITCANCELLATION_SUPPORT    STD_OFF
#define PDUR_RECEIVECANCELLATION_SUPPORT     STD_OFF
#define PDUR_CHANGEPARAMETER_SUPPORT         STD_OFF
#define PDUR_READPARAMETER_SUPPORT           STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Upper and Lower Layer 2PROVIDERXBUFFER_CALLS Switches
 ----------------------------------------------------------------------------- */

#define PDUR_APPLIF_2PROVIDERXBUFFER_CALLS   STD_OFF
#define PDUR_APPLTP_2PROVIDERXBUFFER_CALLS   STD_OFF
#define PDUR_CANIF_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_CANNM_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_CANTP_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_COM_2PROVIDERXBUFFER_CALLS      STD_OFF
#define PDUR_DCM_2PROVIDERXBUFFER_CALLS      STD_OFF
#define PDUR_FRIF_2PROVIDERXBUFFER_CALLS     STD_OFF
#define PDUR_FRNM_2PROVIDERXBUFFER_CALLS     STD_OFF
#define PDUR_FRTP_2PROVIDERXBUFFER_CALLS     STD_OFF
#define PDUR_GW_2PROVIDERXBUFFER_CALLS       STD_OFF
#define PDUR_INVALID_2PROVIDERXBUFFER_CALLS  STD_OFF
#define PDUR_IPDUM_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_J1939TP_2PROVIDERXBUFFER_CALLS  STD_OFF
#define PDUR_LINIF_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_LINTP_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_MOSTIF_2PROVIDERXBUFFER_CALLS   STD_OFF
#define PDUR_MOSTTP_2PROVIDERXBUFFER_CALLS   STD_OFF
#define PDUR_MULTI_2PROVIDERXBUFFER_CALLS    STD_OFF
#define PDUR_NMOSEK_2PROVIDERXBUFFER_CALLS   STD_OFF
#define PDUR_SOAD_2PROVIDERXBUFFER_CALLS     STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Port Defines for each PduR Module Interface
 ----------------------------------------------------------------------------- */

#define PDUR_PORT_APPLIF                     0x00
#define PDUR_PORT_APPLTP                     0x01
#define PDUR_PORT_CANIF                      0x02
#define PDUR_PORT_CANNM                      0x03
#define PDUR_PORT_CANTP                      0x04
#define PDUR_PORT_COM                        0x05
#define PDUR_PORT_DCM                        0x06
#define PDUR_PORT_FRIF                       0x07
#define PDUR_PORT_FRNM                       0x08
#define PDUR_PORT_FRTP                       0x09
#define PDUR_PORT_GW                         0x0A
#define PDUR_PORT_INVALID                    0x0B
#define PDUR_PORT_IPDUM                      0x0C
#define PDUR_PORT_J1939TP                    0x0D
#define PDUR_PORT_LINIF                      0x0E
#define PDUR_PORT_LINTP                      0x0F
#define PDUR_PORT_MOSTIF                     0x10
#define PDUR_PORT_MOSTTP                     0x11
#define PDUR_PORT_MULTI                      0x12
#define PDUR_PORT_NMOSEK                     0x13
#define PDUR_PORT_SOAD                       0x14


/* -----------------------------------------------------------------------------
    &&&~ Upper and Lower Layer TRIGGERTRANSMIT Switches
 ----------------------------------------------------------------------------- */

#define PDUR_APPLIF_TRIGGERTRANSMIT          STD_OFF
#define PDUR_APPLTP_TRIGGERTRANSMIT          STD_OFF
#define PDUR_CANIF_TRIGGERTRANSMIT           STD_OFF
#define PDUR_CANNM_TRIGGERTRANSMIT           STD_ON
#define PDUR_CANTP_TRIGGERTRANSMIT           STD_OFF
#define PDUR_COM_TRIGGERTRANSMIT             STD_OFF
#define PDUR_DCM_TRIGGERTRANSMIT             STD_OFF
#define PDUR_FRIF_TRIGGERTRANSMIT            STD_ON
#define PDUR_FRNM_TRIGGERTRANSMIT            STD_ON
#define PDUR_FRTP_TRIGGERTRANSMIT            STD_OFF
#define PDUR_GW_TRIGGERTRANSMIT              STD_OFF
#define PDUR_INVALID_TRIGGERTRANSMIT         STD_OFF
#define PDUR_IPDUM_TRIGGERTRANSMIT           STD_OFF
#define PDUR_J1939TP_TRIGGERTRANSMIT         STD_OFF
#define PDUR_LINIF_TRIGGERTRANSMIT           STD_ON
#define PDUR_LINTP_TRIGGERTRANSMIT           STD_OFF
#define PDUR_MOSTIF_TRIGGERTRANSMIT          STD_ON
#define PDUR_MOSTTP_TRIGGERTRANSMIT          STD_OFF
#define PDUR_MULTI_TRIGGERTRANSMIT           STD_OFF
#define PDUR_NMOSEK_TRIGGERTRANSMIT          STD_ON
#define PDUR_SOAD_TRIGGERTRANSMIT            STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Transport Protocol Switches for LoTpFromUpTpHandle
 ----------------------------------------------------------------------------- */

#define PDUR_GETLOTPHANDLEFROMUPTPHANDLE     STD_OFF


#define PDUR_CDDDOBT_SUPPORT                 STD_OFF
#define PDUR_IPDUM_OPTIMIZED                 STD_ON
/* END of Checksum include for
  - Gw_AsrPduRPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ General PduR Configuration Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Gw_AsrPduRPrecompileCRC */
#define PDUR_DEV_ERROR_DETECT                STD_OFF
#define PDUR_MULTIPLE_CONFIGURATION          STD_OFF
#define PDUR_PROD_ERROR_DETECT               STD_ON
#define PDUR_VERSION_INFO_API                STD_OFF
#define PDUR_CONFIG_VARIANT                  PDUR_CFGVAR_PRECOMPILETIME
#define PDUR_LIBRARY_SUPPORT                 STD_OFF
#define PDUR_VPB_SUPPORT                     STD_OFF
#define PDUR_GWTP_2PROVIDERXBUFFER_CALLS     STD_OFF
#define PDUR_AR40TP_APISTYLE                 STD_OFF
#define PDUR_ROUTING_2_CSF_SUPPORT           STD_OFF
#define PDUR_ROUTINGPATHGROUP_SUPPORT        STD_OFF
#define PDUR_USE_DYNAMIC_DLC                 STD_ON
#define PDUR_AMD_RUNTIME_MEASUREMENT         STD_OFF
#define PDUR_BALANCE_ROUTING_TIME            STD_ON
#define PDUR_MULTI_TP_TX_SUPPORT             STD_OFF
#define PDUR_GATEWAY_OPERATION               PDUR_GW_SUPPORT
#define PDUR_MULTICAST_FROMTP_SUPPORT        PDUR_MULTI_TP
#define PDUR_MULTICAST_FROMIF_SUPPORT        PDUR_MULTI_COMIF
#define PDUR_CANTPFFSIZE                     6
/* END of Checksum include for
  - Gw_AsrPduRPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ DET Error Ids
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Det Error Ids
 ----------------------------------------------------------------------------- */

/* PduR_CanIfRxIndication */
#define PDUR_FCT_CANIFRXIND                  (uint8) 0xA0
/* PduR_CanIfTxConfirmation */
#define PDUR_FCT_CANIFTXCFM                  (uint8) 0xA1
/* PduR_CanNmCancelTransmitRequest */
#define PDUR_FCT_CANNMTRGTX                  (uint8) 0xA2
/* PduR_CanTpRxIndication */
#define PDUR_FCT_CANTPRXIND                  (uint8) 0xA3
/* PduR_CanTpTxConfirmation */
#define PDUR_FCT_CANTPTXCFM                  (uint8) 0xA4
/* PduR_CanTpProvideRxBuffer */
#define PDUR_FCT_CANTPPRORX                  (uint8) 0xA5
/* PduR_CanTpProvideTxBuffer */
#define PDUR_FCT_CANTPPROTX                  (uint8) 0xA6
/* PduR_ComTransmit */
#define PDUR_FCT_COMTX                       (uint8) 0xA7
/* PduR_DcmTransmit */
#define PDUR_FCT_DCMTX                       (uint8) 0xA8
/* PduR_FrIfCancelTransmitRequest */
#define PDUR_FCT_FRIFTRGTX                   (uint8) 0xA9
/* PduR_FrNmCancelTransmitRequest */
#define PDUR_FCT_FRNMTRGTX                   (uint8) 0xAA
/* PduR_LinIfCancelTransmitRequest */
#define PDUR_FCT_LINIFTRGTX                  (uint8) 0xAB
/* PduR_MostIfCancelTransmitRequest */
#define PDUR_FCT_MOSTIFTRGTX                 (uint8) 0xAC
/* PduR_NmOsekCancelTransmitRequest */
#define PDUR_FCT_NMOSEKTRGTX                 (uint8) 0xAD


/* END of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */


#define PDUR_SB_TX_BUFFER_SUPPORT            STD_OFF
#define PDUR_FIFO_TX_BUFFER_SUPPORT          STD_OFF
#define PDUR_CALLOUT_SUPPORT                 STD_OFF

/* START of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ The ECU Loader use the Init Pointer to choose a required Routing table
 ----------------------------------------------------------------------------- */

#define PDUR_SELECTABLE_INIT_POINTER         STD_OFF


/* END of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Configuration Data Access Macro
 ----------------------------------------------------------------------------- */

/* PRQA S 3410 1 */ /* MD_PduR_3410 */
#define PduR_GetCfgElement(x)                (PduRGlobalConfig.x)
#define PduR_PBConfigStruct                  PduRGlobalConfig


/* START of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */
/*lint -save -e621 */ /* Due to the used communication matrix PDU names can be longer than 31 characters */
/* -----------------------------------------------------------------------------
    &&&~ Rx CanIf Lo Source Handles
 ----------------------------------------------------------------------------- */

#define RxCanIf_CFG_DATA_CODE_REQUEST__CCAN  0
#define RxCanIf_STATUS_C_BCM2__CCAN          1
#define RxCanIf_STATUS_C_IPC__CCAN           2
#define RxCanIf_MOT3__CCAN                   3
#define RxCanIf_BCM_COMMAND__CCAN            4
#define RxCanIf_BSM1__CCAN                   5
#define RxCanIf_MOT1__CCAN                   6


/* -----------------------------------------------------------------------------
    &&&~ Rx CanIf Lo Destination Handles
 ----------------------------------------------------------------------------- */

#define RxCom_Pdu_CFG_DATA_CODE_REQUEST__CCAN 2
#define RxCom_Pdu_STATUS_C_BCM2__CCAN        5
#define RxCom_Pdu_STATUS_C_IPC__CCAN         6
#define RxCom_Pdu_MOT3__CCAN                 4
#define RxCom_Pdu_BCM_COMMAND__CCAN          0
#define RxCom_Pdu_BSM1__CCAN                 1
#define RxCom_Pdu_MOT1__CCAN                 3


/* -----------------------------------------------------------------------------
    &&&~ Rx CanTp Lo Source Handles
 ----------------------------------------------------------------------------- */

#define RxCanTp_DIAGNOSTIC_REQUEST_FUNCTIONAL__CCAN 0
#define RxCanTp_DIAGNOSTIC_REQUEST_EPS__CCAN_EPS 1


/* -----------------------------------------------------------------------------
    &&&~ Rx CanTp Lo Destination Handles
 ----------------------------------------------------------------------------- */

#define RxDcm_DIAGNOSTIC_REQUEST_FUNCTIONAL__CCAN 1
#define RxDcm_DIAGNOSTIC_REQUEST_EPS__CCAN_EPS 0


/* -----------------------------------------------------------------------------
    &&&~ Tx Com Up Source Handles
 ----------------------------------------------------------------------------- */

#define TxCom_Pdu_PDC_INFO_EPS__CCAN         0
#define TxCom_Pdu_CFG_DATA_CODE_RSP_EPS__CCAN 1
#define TxCom_Pdu_GE__CCAN                   2


/* -----------------------------------------------------------------------------
    &&&~ Tx Com Up Destination Handles
 ----------------------------------------------------------------------------- */

#define TxCanIf_PDC_INFO_EPS__CCAN           1
#define TxCanIf_CFG_DATA_CODE_RSP_EPS__CCAN  3
#define TxCanIf_GE__CCAN                     6


/* -----------------------------------------------------------------------------
    &&&~ Tx Dcm Up Source Handles
 ----------------------------------------------------------------------------- */

#define TxDcm_DIAGNOSTIC_RESPONSE_EPS__CCAN  0


/* -----------------------------------------------------------------------------
    &&&~ Tx Dcm Up Destination Handles
 ----------------------------------------------------------------------------- */

#define TxCanTp_DIAGNOSTIC_RESPONSE_EPS__CCAN 0


/*lint -restore */
/* END of Checksum exclude for
  - Gw_AsrPduRPrecompileCRC */



#endif /* PDUR_CFG_H */
