/* -----------------------------------------------------------------------------
  Filename:    PduR_Com.h
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\Synergy\EA3\Working\Fiasa_326_327\Fiasa_326_327_02.02.00\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-10-08  13:13:03
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_COM_H)
#define PDUR_COM_H

/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "PduR.h"


#define PDUR_START_SEC_CODE
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */

/* -----------------------------------------------------------------------------
    &&&~ GLOBAL FUNCTION PROTOTYPES
 ----------------------------------------------------------------------------- */

/**
\brief    The function serves to request the transmission of an IF layer I-PDU.\n
          The PDU Router evaluates the Com I-PDU handle and performs appropriate handle and port conversion.\n
          The call is routed to a lower IF module using the appropriate I-PDU handle of the destination layer.
\param    ComTxPduId        ID of the Com I-PDU to be transmitted
\param    PduInfoPtr        Payload information of the I-PDU (pointer to data and data length)
\return   Std_ReturnType\n
          E_OK              The request was accepted by the PDU Router and by the destination layer.\n
          E_NOT_OK          The PDU Router is in the PDUR_UNINIT state\n
                            or the ComTxPduId is not valid\n
                            or the ComTxPduId is not forwarded in this identity\n
                            or the PduInfoPtr is not valid\n
                            or the request was not accepted by the destination layer.\n
\pre      PduR_Init() is executed successfully and the PDU Router is in PDUR_ONLINE state.
\context  This function can be called on interrupt and task level and has not to be interrupted by other\n
          PduR_ComTransmit calls for the same ComTxPduId.
\note     The function is called by Com.
*/
FUNC(Std_ReturnType, PDUR_CODE) PduR_ComTransmit(PduIdType ComTxPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr);


#define PDUR_STOP_SEC_CODE
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */


#endif /* PDUR_COM_H */
