/* -----------------------------------------------------------------------------
  Filename:    PduR_Lcfg.c
  Description: Toolversion: 18.00.01.01.30.06.49.00.00.00
               
               Serial Number: CBD1300649
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR Fiat SLP4 - MSR Fiat SLP4
                              Micro: 0812BPGEQQ1
                              Compiler: TexasInstruments 4.9.5
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\SynergyProjects\Fiasa_326_327_EPS_TMS570-nzx5jd\Fiasa_326_327_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CCAN":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-05-29  15:06:43
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ MISRA / PCLINT JUSTIFICATION
 ----------------------------------------------------------------------------- */

/* PRQA S 0488 EOF */ /* MD_PduR_0488 */
/* PRQA S 0489 EOF */ /* MD_PduR_0489 */
/* PRQA S 2006 EOF */ /* MD_MSR_14.7 */
/* PRQA S 3109 EOF */ /* MD_MSR_14.3 */
/* PRQA S 3453 EOF */ /* MD_MSR_19.7 */
/*lint -esym(750, PDUR_LCFG_SOURCE) */ /* Identification macro of source file. Required due to Vector coding rules. */


#define PDUR_LCFG_SOURCE
/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "PduR.h"
/*lint -save -e537 */ /* Repeated include required for flexible usage of the communication stack module(s) */
#if ( PDUR_DEV_ERROR_DETECT == STD_ON )
#  include "Det.h"
#endif
#include "PduR_CanIf.h"
#include "PduR_CanTp.h"
#include "PduR_Com.h"
#include "PduR_Dcm.h"
/*lint -save -e960 */ /* MISRA advisory string rule violated by other communication stack module(s) */
/*lint -save -e961 */ /* MISRA advisory string rule violated by other communication stack module(s) */
#include "CanIf.h"
#include "CanTp.h"
#include "Com_Cbk.h"
#include "Dcm_Cbk.h"
/*lint -restore */
/*lint -restore */
/*lint -restore */


/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA PROTOTYPES
 ----------------------------------------------------------------------------- */

#define PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_CONST_UNSPECIFIED
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */

/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_Core_TransmitFctPtrType, PDUR_PBCFG) PduR_Core_TransmitFctPtrTbl[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  CanIf_Transmit /* CanIf */, 
  NULL_PTR /* CanNm */, 
  CanTp_Transmit /* CanTp */, 
  NULL_PTR /* Com */, 
  NULL_PTR /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpIfTriggerTransmitFctPtrType, PDUR_PBCFG) PduR_Core_UpIfTriggerTransmit[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  NULL_PTR /* Com */, 
  NULL_PTR /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpIfTxConfirmationFctPtrType, PDUR_PBCFG) PduR_Core_UpIfTxConfirmation[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  Com_TxConfirmation /* Com */, 
  NULL_PTR /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpIfRxIndicationFctPtrType, PDUR_PBCFG) PduR_Core_UpIfRxIndication[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  Com_RxIndication /* Com */, 
  NULL_PTR /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpTpTxConfirmationFctPtrType, PDUR_PBCFG) PduR_Core_UpTpTxConfirmation[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  NULL_PTR /* Com */, 
  Dcm_TpTxConfirmation /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpTpRxIndicationFctPtrType, PDUR_PBCFG) PduR_Core_UpTpRxIndication[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  NULL_PTR /* Com */, 
  Dcm_TpRxIndication /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpTpProvideRxBufferFctPtrType, PDUR_PBCFG) PduR_Core_UpTpProvideRxBuffer[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  NULL_PTR /* Com */, 
  Dcm_ProvideRxBuffer /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
/* PRQA S 1334 PARAMRXPDUID_1334 */ /* MD_PduR_1334 */
CONST(PduR_UpTpProvideTxBufferFctPtrType, PDUR_PBCFG) PduR_Core_UpTpProvideTxBuffer[21] = 
{
  NULL_PTR /* ApplIf */, 
  NULL_PTR /* ApplTp */, 
  NULL_PTR /* CanIf */, 
  NULL_PTR /* CanNm */, 
  NULL_PTR /* CanTp */, 
  NULL_PTR /* Com */, 
  Dcm_ProvideTxBuffer /* Dcm */, 
  NULL_PTR /* FrIf */, 
  NULL_PTR /* FrNm */, 
  NULL_PTR /* FrTp */, 
  NULL_PTR /* Gw */, 
  NULL_PTR /* Invalid */, 
  NULL_PTR /* IpduM */, 
  NULL_PTR /* J1939Tp */, 
  NULL_PTR /* LinIf */, 
  NULL_PTR /* LinTp */, 
  NULL_PTR /* MostIf */, 
  NULL_PTR /* MostTp */, 
  NULL_PTR /* Multi */, 
  NULL_PTR /* NmOsek */, 
  NULL_PTR /* SoAd */
};
/* PRQA L:PARAMRXPDUID_1334 */
#define PDUR_STOP_SEC_CONST_UNSPECIFIED
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */

#define PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */

#define PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/*lint -save -esym(961, 19.1) */
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"
/*lint -restore */

#define PDUR_START_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define PDUR_STOP_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_CONST_16BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#if (PDUR_ROUTINGPATHGROUP_SUPPORT == STD_ON)
CONST(uint16, PDUR_CONST) pdur_NumberOfRoutingGroupDestPdus = 1;
#endif

#define PDUR_STOP_SEC_CONST_16BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define PDUR_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ GLOBAL FUNCTION PROTOTYPES
 ----------------------------------------------------------------------------- */

#define PDUR_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Gw_AsrPduRLinktimeCRC */
FUNC(Std_ReturnType, PDUR_CODE) PduR_ComTransmit(PduIdType ComTxPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr)
{
  PduR_Det_AssertReturnFuncValue(PduInfoPtr != NULL_PTR, PDUR_FCT_COMTX, PDUR_E_DATA_PTR_INVALID, E_NOT_OK);
  PduR_Det_AssertReturnFuncValue(ComTxPduId < PduR_GetCfgElement(TxCom2LoCnt), PDUR_FCT_COMTX, PDUR_E_PDU_ID_INVALID, E_NOT_OK);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(TxCom2Lo)[ComTxPduId];
    {
      {
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
        if (pDI->destPort == PDUR_PORT_INVALID)
        {
          return E_OK;
        }
  #else
        PduR_Det_AssertReturnFuncValue(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_COMTX, PDUR_E_PDU_ID_INVALID, E_NOT_OK);
  #endif
        {
          PduR_Core_TransmitFctPtrType pDestFunc = PduR_Core_TransmitFctPtrTbl[pDI->destPort];
          if (pDestFunc != NULL_PTR)
          {
            return pDestFunc(pDI->destPduId, PduInfoPtr);
          }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
          else
          {
            PduR_Det_ReportError(PDUR_FCT_COMTX, PDUR_E_PDU_ID_INVALID);
          }
  #endif
        }
      }
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_COMTX, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return E_NOT_OK;
}


FUNC(Std_ReturnType, PDUR_CODE) PduR_DcmTransmit(PduIdType DcmTxPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr)
{
  PduR_Det_AssertReturnFuncValue(PduInfoPtr != NULL_PTR, PDUR_FCT_DCMTX, PDUR_E_DATA_PTR_INVALID, E_NOT_OK);
  PduR_Det_AssertReturnFuncValue(DcmTxPduId < PduR_GetCfgElement(TxDcm2LoCnt), PDUR_FCT_DCMTX, PDUR_E_PDU_ID_INVALID, E_NOT_OK);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(TxDcm2Lo)[DcmTxPduId];
    {
      {
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
        if (pDI->destPort == PDUR_PORT_INVALID)
        {
          return E_OK;
        }
  #else
        PduR_Det_AssertReturnFuncValue(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_DCMTX, PDUR_E_PDU_ID_INVALID, E_NOT_OK);
  #endif
        {
          PduR_Core_TransmitFctPtrType pDestFunc = PduR_Core_TransmitFctPtrTbl[pDI->destPort];
          if (pDestFunc != NULL_PTR)
          {
            return pDestFunc(pDI->destPduId, PduInfoPtr);
          }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
          else
          {
            PduR_Det_ReportError(PDUR_FCT_DCMTX, PDUR_E_PDU_ID_INVALID);
          }
  #endif
        }
      }
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_DCMTX, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return E_NOT_OK;
}


FUNC(void, PDUR_CODE) PduR_CanIfRxIndication(PduIdType CanIfRxPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr)
{
  PduR_Det_AssertReturnFunc(PduInfoPtr != NULL_PTR,PDUR_FCT_CANIFRXIND, PDUR_E_DATA_PTR_INVALID);
  PduR_Det_AssertReturnFunc(CanIfRxPduId < PduR_GetCfgElement(RxCanIf2UpCnt), PDUR_FCT_CANIFRXIND, PDUR_E_PDU_ID_INVALID);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(RxCanIf2Up)[CanIfRxPduId];
    {
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
      if (pDI->destPort != PDUR_PORT_INVALID)
  #else
      PduR_Det_AssertReturnFunc(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANIFRXIND, PDUR_E_PDU_ID_INVALID);
  #endif
      {
        PduR_UpIfRxIndicationFctPtrType pUpIfRxIndicationFctPtr = PduR_Core_UpIfRxIndication[pDI->destPort];
        if (pUpIfRxIndicationFctPtr != NULL_PTR)
        {
          pUpIfRxIndicationFctPtr(pDI->destPduId, PduInfoPtr);
        }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
        else
        {
          PduR_Det_ReportError(PDUR_FCT_CANIFRXIND, PDUR_E_PDU_ID_INVALID);
        }
  #endif
      }
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANIFRXIND, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return;
}


FUNC(void, PDUR_CODE) PduR_CanIfTxConfirmation(PduIdType CanIfTxPduId)
{
  PduR_Det_AssertReturnFunc(PduR_GetCfgElement(TxCanIf2Up)[CanIfTxPduId].destPort!= PDUR_PORT_INVALID,PDUR_FCT_CANIFTXCFM, PDUR_E_PDU_ID_INVALID);
  PduR_Det_AssertReturnFunc(CanIfTxPduId < PduR_GetCfgElement(TxCanIf2UpCnt), PDUR_FCT_CANIFTXCFM, PDUR_E_PDU_ID_INVALID);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(TxCanIf2Up)[CanIfTxPduId];
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
    if (pDI->destPort != PDUR_PORT_INVALID)
  #else
    PduR_Det_AssertReturnFunc(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANIFTXCFM, PDUR_E_PDU_ID_INVALID);
  #endif
    {
      PduR_UpIfTxConfirmationFctPtrType pUpIfTxConfirmationFctPtr = PduR_Core_UpIfTxConfirmation[pDI->destPort];
      if (pUpIfTxConfirmationFctPtr != NULL_PTR)
      {
        pUpIfTxConfirmationFctPtr(pDI->destPduId);
      }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
      else
      {
        PduR_Det_ReportError(PDUR_FCT_CANIFTXCFM, PDUR_E_PDU_ID_INVALID);
      }
  #endif
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANIFTXCFM, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return;
}


FUNC(void, PDUR_CODE) PduR_CanTpRxIndication(PduIdType CanTpRxPduId, NotifResultType Result)
{
  PduR_Det_AssertReturnFunc(PduR_GetCfgElement(RxCanTp2Up)[CanTpRxPduId].destPort!= PDUR_PORT_INVALID,PDUR_FCT_CANTPRXIND, PDUR_E_PDU_ID_INVALID);
  PduR_Det_AssertReturnFunc(CanTpRxPduId < PduR_GetCfgElement(RxCanTp2UpCnt), PDUR_FCT_CANTPRXIND, PDUR_E_PDU_ID_INVALID);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(RxCanTp2Up)[CanTpRxPduId];
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
    if (pDI->destPort != PDUR_PORT_INVALID)
  #else
    PduR_Det_AssertReturnFunc(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANTPRXIND, PDUR_E_PDU_ID_INVALID);
  #endif
    {
      PduR_UpTpRxIndicationFctPtrType pUpTpRxIndicationFctPtr = PduR_Core_UpTpRxIndication[pDI->destPort];
      if (pUpTpRxIndicationFctPtr != NULL_PTR)
      {
        pUpTpRxIndicationFctPtr(pDI->destPduId, Result);
      }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
      else
      {
        PduR_Det_ReportError(PDUR_FCT_CANTPRXIND, PDUR_E_PDU_ID_INVALID);
      }
  #endif
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANTPRXIND, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return;
}


FUNC(void, PDUR_CODE) PduR_CanTpTxConfirmation(PduIdType CanTpTxPduId, NotifResultType Result)
{
  PduR_Det_AssertReturnFunc(PduR_GetCfgElement(TxCanTp2Up)[CanTpTxPduId].destPort!= PDUR_PORT_INVALID,PDUR_FCT_CANTPTXCFM, PDUR_E_PDU_ID_INVALID);
  PduR_Det_AssertReturnFunc(CanTpTxPduId < PduR_GetCfgElement(TxCanTp2UpCnt), PDUR_FCT_CANTPTXCFM, PDUR_E_PDU_ID_INVALID);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(TxCanTp2Up)[CanTpTxPduId];
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
    if (pDI->destPort != PDUR_PORT_INVALID)
  #else
    PduR_Det_AssertReturnFunc(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANTPTXCFM, PDUR_E_PDU_ID_INVALID);
  #endif
    {
      PduR_UpTpTxConfirmationFctPtrType pUpTpTxConfirmationFctPtr = PduR_Core_UpTpTxConfirmation[pDI->destPort];
      if (pUpTpTxConfirmationFctPtr != NULL_PTR)
      {
        pUpTpTxConfirmationFctPtr(pDI->destPduId, Result);
      }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
      else
      {
        PduR_Det_ReportError(PDUR_FCT_CANTPTXCFM, PDUR_E_PDU_ID_INVALID);
      }
  #endif
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANTPTXCFM, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return;
}


FUNC(BufReq_ReturnType, PDUR_CODE) PduR_CanTpProvideRxBuffer(PduIdType CanTpRxPduId, PduLengthType TpSduLength, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr)
{
  BufReq_ReturnType retVal = BUFREQ_E_NOT_OK;
  PduR_Det_AssertReturnFuncValue(PduR_GetCfgElement(RxCanTp2Up)[CanTpRxPduId].destPort!= PDUR_PORT_INVALID,PDUR_FCT_CANTPPRORX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  PduR_Det_AssertReturnFuncValue(CanTpRxPduId < PduR_GetCfgElement(RxCanTp2UpCnt), PDUR_FCT_CANTPPRORX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(RxCanTp2Up)[CanTpRxPduId];
    {
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
      if (pDI->destPort != PDUR_PORT_INVALID)
  #else
      PduR_Det_AssertReturnFuncValue(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANTPPRORX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  #endif
      {
        PduR_UpTpProvideRxBufferFctPtrType pUpTpProvideRxBufferFctPtr = PduR_Core_UpTpProvideRxBuffer[pDI->destPort];
        if (pUpTpProvideRxBufferFctPtr != NULL_PTR)
        {
              retVal = pUpTpProvideRxBufferFctPtr(pDI->destPduId, TpSduLength, PduInfoPtr);
        }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
        else
        {
          PduR_Det_ReportError(PDUR_FCT_CANTPPRORX, PDUR_E_PDU_ID_INVALID);
        }
  #endif
      }
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANTPPRORX, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return retVal;
}


FUNC(BufReq_ReturnType, PDUR_CODE) PduR_CanTpProvideTxBuffer(PduIdType CanTpTxPduId, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr, PduLengthType Length)
{
  PduR_Det_AssertReturnFuncValue(PduR_GetCfgElement(TxCanTp2Up)[CanTpTxPduId].destPort!= PDUR_PORT_INVALID,PDUR_FCT_CANTPPROTX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  PduR_Det_AssertReturnFuncValue(CanTpTxPduId < PduR_GetCfgElement(TxCanTp2UpCnt), PDUR_FCT_CANTPPROTX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  
  if(PDUR_ONLINE == PduR_Core_GetState())
  {
    PduR_Core_DestITypePtr pDI;
    pDI = &PduR_GetCfgElement(TxCanTp2Up)[CanTpTxPduId];
  #if (PDUR_MULTIPLE_CONFIGURATION == STD_ON)
    if (pDI->destPort != PDUR_PORT_INVALID)
  #else
    PduR_Det_AssertReturnFuncValue(pDI->destPort != PDUR_PORT_INVALID, PDUR_FCT_CANTPPROTX, PDUR_E_PDU_ID_INVALID, BUFREQ_E_NOT_OK);
  #endif
    {
      {
        PduR_UpTpProvideTxBufferFctPtrType pUpTpProvideTxBufferFctPtr = PduR_Core_UpTpProvideTxBuffer[pDI->destPort];
        if(pUpTpProvideTxBufferFctPtr != NULL_PTR)
        {
          return pUpTpProvideTxBufferFctPtr(pDI->destPduId, PduInfoPtr, Length);
        }
      }
      PduR_Det_ReportError(PDUR_FCT_CANTPPROTX, PDUR_E_PDU_ID_INVALID);
    }
  }
  #if (PDUR_DEV_ERROR_DETECT == STD_ON)
  else
  {
    PduR_Det_ReportError(PDUR_FCT_CANTPPROTX, PDUR_E_INVALID_REQUEST);
  }
  #endif
  return BUFREQ_E_NOT_OK;
}


/* END of Checksum include for
  - Gw_AsrPduRLinktimeCRC */

#define PDUR_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"





